### ISSUE TITLE
Exclusions list: Defer restarting services by default

### ISSUE THREAD

**Issue by stdedos** [liske/needrestart#102]
There is a number of reasons for that:

- `dbus.service` on Ubuntu can only be restarted as a side-effect, not directly
- 'Critical services' for whatever sysadmin reason (stupid e.g.: unacceptable `nginx` restart)
- 'Services that crash everything': -_examples to come_- Got them: `systemd-manager` and `systemd-udevd.service`

Not from the same system, but representative none-the-less:
```
[*] apache2.service
[ ] dbus.service
[ ] docker.service
[ ] getty@tty1.service???
[ ] libvirt-bin.service
[*] nfs-mountd.service
[*] rsyslog.service
[*] systemd-manager??
[*] systemd-udevd.service??
[*] zed.service
```

and

```
# service --status-all
 [ + ]  acpid
 [ + ]  apache-htcacheclean
 [ + ]  apache2
 [ + ]  apparmor
 [ + ]  apport
 [ + ]  atd
 [ - ]  bind9
 [ - ]  bootmisc.sh
 [ + ]  cgmanager
 [ - ]  cgproxy
 [ - ]  checkfs.sh
 [ - ]  checkroot-bootclean.sh
 [ - ]  checkroot.sh
 [ + ]  console-setup
 [ + ]  cron
 [ - ]  cryptdisks
 [ - ]  cryptdisks-early
 [ + ]  dataeng
 [ + ]  dbus
 [ + ]  docker
 [ + ]  dsm_om_connsvc
 [ - ]  dsm_sa_ipmi
 [ + ]  ebtables
 [ + ]  grub-common
 [ - ]  hostname.sh
 [ - ]  hwclock.sh
 [ - ]  instsvcdrv
 [ + ]  irqbalance
 [ + ]  iscsid
 [ + ]  jenkins
 [ + ]  keyboard-setup
 [ - ]  killprocs
 [ + ]  kmod
 [ + ]  libvirt-bin
 [ + ]  libvirt-guests
 [ - ]  lvm2
 [ + ]  lvm2-lvmetad
 [ + ]  lvm2-lvmpolld
 [ + ]  lxcfs
 [ - ]  lxd
 [ + ]  mdadm
 [ - ]  mdadm-waitidle
 [ - ]  mountall-bootclean.sh
 [ - ]  mountall.sh
 [ - ]  mountdevsubfs.sh
 [ - ]  mountkernfs.sh
 [ - ]  mountnfs-bootclean.sh
 [ - ]  mountnfs.sh
 [ + ]  nagios3
 [ + ]  networking
 [ + ]  nfs-kernel-server
 [ - ]  nginx
 [ + ]  ondemand
 [ + ]  open-iscsi
 [ - ]  open-vm-tools
 [ + ]  openipmi
 [ - ]  plymouth
 [ - ]  plymouth-log
 [ + ]  procps
 [ + ]  qemu-kvm
 [ + ]  rc.local
 [ + ]  resolvconf
 [ + ]  rpcbind
 [ - ]  rsync
 [ + ]  rsyslog
 [ - ]  screen-cleanup
 [ - ]  sendsigs
 [ + ]  sfcb
 [ + ]  smartmontools
 [ + ]  ssh
 [ + ]  swapspace
 [ + ]  udev
 [ + ]  ufw
 [ - ]  umountfs
 [ - ]  umountnfs.sh
 [ - ]  umountroot
 [ + ]  unattended-upgrades
 [ + ]  urandom
 [ + ]  uuidd
 [ - ]  virtlockd
 [ - ]  virtlogd
 [ - ]  x11-common
 [ + ]  zfs-share
```

_Especially for the last part:_ Is there any "logging-per-invocation" stored somewhere? In my last update I was prompted to restart -`system.service` and `system-udev.service`- `systemd-manager` and `systemd-udevd.service`, but `service --status-all` does not show them.

Also `getty@tty1.service` _definitely_ does not look like a service

_I suspect_ that those are the services that completely broke my X environment (hence forcing a restart)

**Comment by liske** [comment]
Which version of needrestart do you use? Those critical services are not selected by default and there is a are handlers for special services like udev or systemd-manager. Maybe you won't to give the most recent package from [Debian experimantal](https://packages.debian.org/experimental/needrestart) a try since it contains many bugfixes.

The `service` command is not part of systemd so it might not know all systemd units (services, sockets, sessions).

`getty@tty.service` is a valid service, this is how systemd spawns the text console TTYs.

**Comment by stdedos** [comment]
@liske I keep on pulling master. Daily :-D

My definition of restarting is, if everything can 'come back up relatively easy'. So, for example:
* I don't mind an Apache, since nothing serious can arise from it (for me)
* I do mind restarting (whatever crashed my X Session). That's mainly the reason I don't restart my computer, since, opening and re-arranging 10-15 windows in 9 virtual desktops, does take a while.

_I am bad at management and keeping only the necessary things open, but, well ... Who's perfect?_

_Disclaimer: I did write the bug report directly after the restart. You are right I might not know nearly enough._
_I guess heat of the moment? Apologies_

**Comment by stdedos** [comment]
Umm @liske, any uninstallation instructions?

I expected at least your Makefile to have a `make uninstall`, but that's not the case

**Comment by stdedos** [comment]
I am still getting "recommendations" to restart `lightdm.service`

```
Restarting services...
 systemctl restart accounts-daemon.service avahi-daemon.service colord.service cups-browsed.service cups.service fwupd.service ModemManager.service NetworkManager.service polkitd.service rtkit-daemon.service ssh.service systemd-journald.service teamviewerd.service thermald.service udisks2.service upower.service uuidd.service vmware-workstation-server.service whoopsie.service xpra.service
Service restarts being deferred:
 /etc/needrestart/restart.d/dbus.service
 systemctl restart lightdm.service
```

```
$ needrestart --version

needrestart 3.2 - Restart daemons after library updates.

Authors:
  Thomas Liske <thomas@fiasko-nw.net>

Copyright Holder:
  2013 - 2018 (C) Thomas Liske [http://fiasko-nw.net/~thomas/]

Upstream:
  https://github.com/liske/needrestart

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

needrestart$ (master u=) git log -1 --oneline 
7626e69 (HEAD -> master, tag: v3.2, origin/master, origin/HEAD) Release needrestart 3.2.
```
