### ISSUE TITLE
restart.d/dbus.service: Unused RESTART_ADD should be RESTART_SVC?

### ISSUE THREAD

**Issue by alexbarton** [liske/needrestart#104]
https://github.com/liske/needrestart/blob/160fe95d75a3d867dde1125dbea2b70b2088f464/ex/restart.d/dbus.service#L34

But `RESTART_ADD` isn't used afterwards?

So I think this should be `RESTART_SVC`, which is used to restart services afterwards:

https://github.com/liske/needrestart/blob/160fe95d75a3d867dde1125dbea2b70b2088f464/ex/restart.d/dbus.service#L50

**Comment by liske** [comment]
Thanks!
