### ISSUE TITLE
Needs option to restart services automatically only when run non-interactively

### ISSUE THREAD

**Issue by fhimpe** [liske/needrestart#109]
I would like needrestart to restart services automatically only when it is started from unattended-upgrades, but not when it is run when I start apt-get upgrade manually in a shell. In that case, I want it to run interactively. It seems currently it is only possible to always restart services automatically or always interactively (with fallback to list-only).

**Comment by liske** [comment]
Needrestart's configuration file is perl, maybe it is possible to add some logic to detect if needrestart is run by unattended-upgrades (maybe due to some environment variables?) and set `$nrconf{restart}` accordingly.

**Comment by liske** [comment]
With needrestart 3.0 and later you could also set the `NEEDRESTART_MODE` environment variable to override the config file.

**Comment by vmeurisse** [comment]
In case anyone else is looking for a solution.

Create a file `/etc/needrestart/conf.d/restart.conf` with this content:
```perl
# Restart mode: (l)ist only, (i)nteractive or (a)utomatically.
#
# Default is to fallback from (i)nteractive to (l)ist only if dpkg is non-interactive
# We want to switch to (a)utomatically so services are correctly restarted if run by unattended-upgrade
#
$nrconf{restart} = exists($ENV{DEBIAN_FRONTEND}) && $ENV{DEBIAN_FRONTEND} eq 'noninteractive' ? 'a' : 'i';
```
