### ISSUE TITLE
False positive 'pending kernel upgrade' warning

### ISSUE THREAD

**Issue by glitsj16** [liske/needrestart#111]
Hi, I've been wondering how to avoid a `Pending kernel upgrade!` warning when one has `2 (or more) kernels` installed. On Ubuntu this is quite common, as I'm sure it is on many other distributions. When booted into a different kernel than what needrestart considers to be the expected one, it keeps throwing the warning. Falsely in my opinion, because there isn't any kernel upgrade pending. The machine just happens to be booted in one of several already fully installed kernels.

```
$ lsb_release -d
Description:	Ubuntu 16.04.4 LTS

$  sudo ls /boot | grep vmlinuz
vmlinuz-4.13.0-38-generic
vmlinuz-4.15.0-15.1-liquorix-amd64

$ uname -r
4.13.0-38-generic

$ sudo LC_ALL=C needrestart -k -v
[main] eval /etc/needrestart/needrestart.conf
[main] needrestart v3.2
[main] running in root mode
[Core] Using UI 'NeedRestart::UI::stdio'...
[main] systemd detected
[Kernel] Linux: kernel release 4.13.0-38-generic, kernel version #43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018
Failed to load NeedRestart::Kernel::kFreeBSD: [Kernel/kFreeBSD] Not running on GNU/kFreeBSD!
[Kernel/Linux] /boot/vmlinuz-4.15.0-15.1-liquorix-amd64 => 4.15.0-15.1-liquorix-amd64 (steven@liquorix.net) #1 ZEN SMP PREEMPT liquorix 4.15-9ubuntu1~xenial (2018-04-05) [4.15.0-15.1-liquorix-amd64]
[Kernel/Linux] /boot/vmlinuz-4.13.0-38-generic => 4.13.0-38-generic (buildd@lgw01-amd64-027) #43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018 [4.13.0-38-generic]*
[Kernel/Linux] Expected linux version: 4.15.0-15.1-liquorix-amd64

Pending kernel upgrade!

Running kernel version:
  4.13.0-38-generic

Diagnostics:
  The currently running kernel version is not the expected kernel version
4.15.0-15.1-liquorix-amd64.

Restarting the system to load the new kernel will not be handled automatically, so you should
consider rebooting. [Return]

```
Is there a documented workaround somewhere on how to avoid this?

Regards

**Comment by liske** [comment]
Hi,

this is currently not possible with needrestart. What is the use case to have multiple kernel releases installed in parallel? I don't think this is a common setup.

Regards,
Thomas

**Comment by glitsj16** [comment]
@liske Thanks for your response. As to the use case to have at least 2 kernels installed, I can only refer to 'good practice'. What does one do when a newly installed kernel refuses to boot properly (for whatever reason) and you don't have a fallback kernel installed from which to:
- ensure prolonged machine availability;
- troubleshoot the issue?

In this context I didn't get what you mean by `in parallel`, but that's beside my main observation here.

'Good practice' is neither a clear-cut category, nor a decisive argument, I do realize that. Yet, there is no downside to having multiple kernels, as long as you know they work with your system and don't run out of disk space. Having an extra `known-to-boot-properly` fallback kernel is precisely why both RedHat and Debian-based distributions keep several kernels when you install a new one using yum or apt-get by default.

In RedHat distros the number of kernels to keep is controlled via /etc/yum.conf with the `installonly_limit` setting (defaults to 5). Debian-based distros keep old kernels but don't automatically remove them. The latter have the `purge-old-kernels` command to cleanup kernel/header packages. By default, that also will keep at least the latest 2 kernels (see [man page here](http://manpages.ubuntu.com/manpages/xenial/en/man1/purge-old-kernels.1.html)). In my opinion this hints on the 'good practice' I referred to earlier. Why would these widely-used distros have these defaults? Like so many other things in life, kernel upgrading isn't without possible issues. Erring on the side of caution can and has saved many from needless  hairpulling :smile:.

Regards

**Comment by liske** [comment]
I agree that it is common to have different kernel versions installed on the same time but I would expect that the most recent (read: highest version) should be used. This is the same how update-grub builds it's config - the highest version will be boot by default. In this case needrestart does work as expected.

If you do not run the highest version due to missing reboot or a problem with the new kernel image I think it is valid for needrestart to report this issue to the user since he is still running an outdated image.

**Comment by glitsj16** [comment]
Fair enough. I guess I interpreted needrestart's -k switch to only report on a `newly installed` kernel. Thanks for your time.

**Comment by clst** [comment]
This would be really helpful. I use the default arch kernel for work and the -zen kernel for gaming.

When I am not on -zen needrestart complains about the kernel even if the version numbers are the same.

**Comment by Faerbit** [comment]
> but I would expect that the most recent (read: highest version) should be used. [...] In this case needrestart does work as expected.

It doesn't for me though:
```
% needrestart -k   
Scanning linux images...                                                                                                                                     

The currently running kernel version is 6.15.9-arch1-1 which is not the expected kernel version 6.12.41-1-lts.
```

Can I configure the expected kernel version somehow?
