### ISSUE TITLE
Default config raises errors

### ISSUE THREAD

**Issue by xschlef** [liske/needrestart#114]
Hi,

my perl is not the best, but the current default configuration triggers interpreter warnings on older debian systems. (perl 5.20.2)

`
 Useless use of '\'; doesn't escape metacharacter '(' at (eval 16) line 163, <> line 1. 
 Useless use of '\'; doesn't escape metacharacter '(' at (eval 16) line 172, <> line 1.
`

Escaping said strings with \Q and \E resolves those errors.

Thanks.

**Comment by liske** [comment]
Hi,

this is a bug in some older perl versions (like on Debian Jessie). I won't change it upstream since it is not a bug in needrestart.

Regards,
Thomas
