### ISSUE TITLE
check applications outside of apt-get/dpkg?

### ISSUE THREAD

**Issue by adrelanos** [liske/needrestart#12]
Can needrestart help to monitor applications outside of apt-get/dpkg?

Specifically I am talking about the Tor Browser Bundle. It's supposed to be installed in the user's home folder. Unfortunately, there is no debian package of it. It updates itself through its automatic updater. But specifically when running it headless, it's difficult to detect if it need restart.

**Comment by liske** [comment]
System-V: *needrestart* uses '/etc/needrestart/hook.d' to find the binary's package and look into the package file list to detected the package's/binary's Sys-V init script.

systemd: *needrestart* uses the service name from `/proc/$PID/cgroup` if available

*needrestart* is designed to restart binaries... you might use:
```console
$ /usr/sbin/needrestart -r l -b
NEEDRESTART-VER: 2.1
NEEDRESTART-PID: gajim=4676
...
```
as a normal user to get your binaries requiring a restart.


HTH,
Thomas
