### ISSUE TITLE
configuration file is ignored

### ISSUE THREAD

**Issue by shartge** [liske/needrestart#121]
This is from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902031#17

> The bug is in commit dd7f10172a7f6163b906b23297898ac1ac164210. The
> problem is that the last command in the block changed. So the return
> value of <$fh> is ignored and hence the entire configuration, too.

Also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902049 and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=901999

Reverting dd7f10172a7f6163b906b23297898ac1ac164210 restores correct working behaviour.

**Comment by liske** [comment]
Thanks! I'm going to release the fix ASAP.
