### ISSUE TITLE
Showing new kernel on OpenVZ machines

### ISSUE THREAD

**Issue by yangzhaofeng** [liske/needrestart#126]
I am using needresrart 2.11 on Debian 9.5 (in OpenVZ with kernel 4.9.0). It shows that I should update the kernel, which I can not update.
![image](https://user-images.githubusercontent.com/5832364/44969319-3d5ccf00-af7f-11e8-8293-e11b013a367d.png)
What's more, the latest kernel version is `4.9.0-8-amd64`. How does the program get `4.9.0-6`?

**Comment by liske** [comment]
Please provide the output of `needrestart -v`.

**Comment by yangzhaofeng** [comment]
`
[main] eval /etc/needrestart/needrestart.conf
[main] needrestart v2.11
[main] running in root mode
[Core] Using UI 'NeedRestart::UI::stdio'...
[main] detected systemd
[Kernel] Linux: kernel release 4.9.0, kernel version #1 SMP Wed May 23 10:04:13 MSK 2018
[Kernel/Linux] /boot/vmlinuz => 4.9.0-6-amd64 (debian-kernel@lists.debian.org) #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) [4.9.0-6-amd64]
[Kernel/Linux] Expected linux version: 4.9.0-6-amd64
Pending kernel upgrade!

Running kernel version:
  4.9.0

Diagnostics:
  The currently running kernel version is not the expected kernel version 4.9.0-6-amd64.

Restarting the system to load the new kernel will not be handled automatically, so you should consider rebooting.
[Return]

No services need to be restarted.
No containers need to be restarted.
No user sessions are running outdated binaries.
`

I have installed `needrestart v3.3` from stretch-backports. Now there is no problem. Thanks!
