### ISSUE TITLE
please explain how to extend $nrconf{override_rc} by drop-in

### ISSUE THREAD

**Issue by adrelanos** [liske/needrestart#13]
Could you explain please, how one can extend $nrconf{override_rc} with one package by using a drop-in? I mean, while keeping the defaults intact. Injecting extra items into $nrconf{override_rc}. This is non-trivial for non-perl speaking people. Please provide an example.

**Comment by liske** [comment]
Hi,

* example:
```perl
$nrconf{override_rc}->{q(^example)} = 0;
$nrconf{override_rc}->{q(^foobar)} = 0;
```
* put into a file at `/etc/needrestart/conf.d`

HTH,
Thomas

**Comment by adrelanos** [comment]
Thank you!
