### ISSUE TITLE
Wrong microcode suggestion?

### ISSUE THREAD

**Issue by mtrp12** [liske/needrestart#136]
This is the iucode_tool command output:

    iucode_tool: system has processor(s) with signature 0x000306f2
    microcode bundle 1: /boot/initrd.img-4.15.0-38-generic
    selected microcodes:
      001/074: sig 0x000306f2, pf_mask 0x6f, 2018-04-20, rev 0x003d, size 33792
      001/075: sig 0x000306f4, pf_mask 0x80, 2018-04-20, rev 0x0012, size 17408

It says, according to my interpretation, version 0x003d is the correct microcode version for my cpu with signature 0x000306f2. But needrestart is nagging me to use 0x0012, which did not get activated after any amount of restart.

I am using ubuntu 18.04.01.

**Comment by liske** [comment]
Which version of needrestart did you use? I would expect something before 3.2 since there was a fix which should prevent this false positive (see also #112) in older releases.

**Comment by mtrp12** [comment]
Apparently it's version 3.1. So, I guess I need to wait for update from the repo. Thanks.
