### ISSUE TITLE
Don't check microcode updates in VM

### ISSUE THREAD

**Issue by tobby88** [liske/needrestart#139]
Hi

In my VM it complains about my microcode (German: "Die laufende Prozessor Mikrocode-Revision ist 0x1, es wird jedoch die Revision 0xc6 erwaret."). Since this is a VM it is not necessary to check the microcode, it is handled by my hypervisor.

> tobby@template-ubuntu-1804:~$ sudo systemd-detect-virt
> kvm

> tobby@template-ubuntu-1804:~$ cat /proc/cpuinfo
> processor       : 0
> vendor_id       : GenuineIntel
> cpu family      : 6
> model           : 94
> model name      : Intel Core Processor (Skylake, IBRS)
> stepping        : 3
> microcode       : 0x1
> cpu MHz         : 3696.000
> cache size      : 16384 KB
> physical id     : 0
> siblings        : 2
> core id         : 0
> cpu cores       : 2
> apicid          : 0
> initial apicid  : 0
> fpu             : yes
> fpu_exception   : yes
> cpuid level     : 13
> wp              : yes
> flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap xsaveopt xsavec xgetbv1 arat
> bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
> bogomips        : 7392.00
> clflush size    : 64
> cache_alignment : 64
> address sizes   : 40 bits physical, 48 bits virtual
> power management:

> tobby@template-ubuntu-1804:~$ dmesg | grep Hypervisor
> [    0.000000] Hypervisor detected: KVM

> tobby@template-ubuntu-1804:~$ lscpu | grep Hypervisor
> Hypervisor-Anbieter:     KVM

Any way to skip microcode checks in a KVM environment?

**Comment by liske** [comment]
Thanks for the idea using `systemd-detect-virt`. I've patched needrestart so it will detect if it is running inside a container *or* vm.
