### ISSUE TITLE
How does needrestart determine expected kernel version?

### ISSUE THREAD

**Issue by bjmgeek** [liske/needrestart#14]
I'm running kernel 4.0.0, which I built from source using make-kpkg.  I installed the resulting debs, and rebooted the system into my new kernel.  All is well, except needrestart keeps telling me the running kernel doesn't match the expected version.

````
bminton:~# needrestart -k
Scanning linux images...
Pending kernel upgrade
----------------------

Newer kernel available

The currently running kernel version is 4.0.0 which is not the expected kernel version 3.17.4.

Restarting the system to load the new kernel will not be handled automatically, so you should consider rebooting.

bminton:~# dpkg -l |grep linux-image
ii  linux-image-4.0.0                                           4.0.0-10.00.Custom                                   amd64        Linux kernel binary image for version 4.0.0
````

So, my question is, where is it getting the 3.17.4 version from?

**Comment by liske** [comment]
Hi,

could you please provide the output of `needrestart -v`? Which Linux distri and *needrestart* version did you use? There was a bug (Debian Bug#781657) in the kernel version comparing... but it was fixed in needrestart since versions 1.2-8 and 2.1-1.


HTH,
Thomas

**Comment by bjmgeek** [comment]
bminton:~# needrestart -v
[main] eval /etc/needrestart/needrestart.conf
[main] running in root-mode
[Core] Using UI 'NeedRestart::UI::stdio'...
[main] detected systemd
[Core] #2176 is a NeedRestart::Interp::Python
[Python] #2176: could not get a source file, skipping
[Core] #5137 is a NeedRestart::Interp::Python
[Core] #5211 is a NeedRestart::Interp::Perl
[Core] #5603 is a NeedRestart::Interp::Perl
[Perl] #5603: could not get a source file, skipping
[Core] #5771 is a NeedRestart::Interp::Python
[Core] #5795 is a NeedRestart::Interp::Perl
[Core] #5877 is a NeedRestart::Interp::Perl
[Core] #6444 is a NeedRestart::Interp::Perl
[Core] #6891 is a NeedRestart::Interp::Java
[Core] #8315 is a NeedRestart::Interp::Perl
[main] #10858 uses non-existing /usr/sbin/avahi-daemon
[main] #10858 is not a child
[main] #21404 uses non-existing /usr/lib/rtkit/rtkit-daemon
[main] #21404 is not a child
[main] #21408 uses non-existing /usr/sbin/scanlogd
[main] #21408 is not a child
[main] #21412 uses non-existing /lib/x86_64-linux-gnu/libdl-2.19.so
[main] #21412 is a child of #21410
[Core] #23165 is a NeedRestart::Interp::Perl
[main] #10858 exe => /usr/sbin/avahi-daemon
[main] #10858 is avahi-daemon.service
[main] #21404 exe => /usr/lib/rtkit/rtkit-daemon
[main] #21404 is rtkit-daemon.service
[main] #21408 exe => /usr/sbin/scanlogd
[main] #21408 is scanlogd.service
[main] #21410 exe => /usr/sbin/dovecot
[main] #21410 is dovecot.service
[Kernel] Linux: kernel release 4.0.0, kernel version #1 SMP Mon Apr 13
11:08:28 EDT 2015
[Kernel/Linux] /boot/vmlinuz.old => 3.4.3 (root@bminton.is-a-geek.net) #5
SMP Fri Jun 22 20:16:56 UTC 2012 [3.4.3]
[Kernel/Linux] /boot/vmlinuz-3.17.4 => 3.17.4 (root@bminton.is-a-geek.net)
#1 SMP Tue Nov 25 16:22:28 EST 2014 [3.17.4]
[Kernel/Linux] /boot/vmlinuz-3.16.0-4-amd64 => 3.16.0-4-amd64 (
debian-kernel@lists.debian.org) #1 SMP Debian 3.16.7-ckt4-3 (2015-02-03)
[3.16.0-4-amd64]
[Kernel/Linux] /boot/vmlinuz-3.16-3-amd64 => 3.16-3-amd64 (
debian-kernel@lists.debian.org) #1 SMP Debian 3.16.5-1 (2014-10-10)
[3.16-3-amd64]
[Kernel/Linux] /boot/vmlinuz-3.7.0 => 3.7.0 (root@bminton.is-a-geek.net) #1
SMP Tue Dec 11 20:53:08 UTC 2012 [3.7.0]
[Kernel/Linux] /boot/vmlinuz-3.4.3 => 3.4.3 (root@bminton.is-a-geek.net) #5
SMP Fri Jun 22 20:16:56 UTC 2012 [3.4.3]
[Kernel/Linux] /boot/vmlinuz-3.1.6.old => 3.1.6 (root@bminton.is-a-geek.net)
#1 SMP Sat Jan 7 12:05:54 EST 2012 [3.1.6]
[Kernel/Linux] /boot/vmlinuz-2.6.35.5.old => 2.6.35.5 (
root@bminton.is-a-geek.net) #2 SMP Wed Sep 22 02:11:40 EDT 2010 [2.6.35.5]
[Kernel/Linux] /boot/vmlinuz-2.6.31 => 2.6.31 (bminton@bminton.is-a-geek.net)
#1 SMP Fri Sep 11 17:20:59 EDT 2009 [2.6.31]
[Kernel/Linux] /boot/vmlinuz => 3.7.0 (root@bminton.is-a-geek.net) #1 SMP
Tue Dec 11 20:53:08 UTC 2012 [3.7.0]
[Kernel/Linux] Expected linux version: 3.17.4
Pending kernel upgrade!

Running kernel version:
  4.0.0

Diagnostics:
  The currently running kernel version is not the expected kernel version
3.17.4.

Restarting the system to load the new kernel will not be handled
automatically, so you should consider rebooting. [Return]

Services to be restarted:
Restart avahi-daemon.service? [Ynas?] a
Restart dovecot.service? [Ynas?] yes
Restart rtkit-daemon.service? [Ynas?] yes
Restart scanlogd.service? [Ynas?] yes
Restarting services using systemd...
No containers need to be restarted.
bminton:~#

**Comment by liske** [comment]
Re,

*needrestart* does not find your kernel image file (no `[Kernel/Linux]` line with a 4.0.0). Since your kernel seems not be installed it is handled as a pending kernel upgrade.


HTH,
Thomas

**Comment by bjmgeek** [comment]
Thanks. I realized /boot was not mounted. There was a 3.17.4 kernel sitting
on /boot in the root volume.  Mounting /boot fixed the problem. Now to
figure out why /boot isn't mounting at system startup. :-)

**Comment by bjmgeek** [comment]
It would be great for the man page to mention that it looks in /boot.
