### ISSUE TITLE
Selected Vs Unselected Services

### ISSUE THREAD

**Issue by gaia** [liske/needrestart#143]
Why does it select some services, but not others, on any given restart list?

In other words, why does an unselected service show up on the list?

```
[*] apache2.service
[ ] dbus.service
[ ] docker.service
[ ] libvirt-bin.service
[*] nfs-mountd.service
[*] rsyslog.service
[*] zed.service
```

**Comment by liske** [comment]
Restarting services might result in disruption of important system services. Restarting the display manager on a desktop computer might be a bad idea since it would kill the user's GUI session.

**Comment by gaia** [comment]
So the recommendation when there are unselected services (no GUI) is to restart the box?

**Comment by stdedos** [comment]
Yes. Or, you can try it at your own risk to see what does it do :smiley: 

```
[ ] dbus.service
```
_Baaaaaad idea_
