### ISSUE TITLE
Raspbian has 2 kernel Image files.

### ISSUE THREAD

**Issue by takichikawa** [liske/needrestart#146]
Raspbian(debian/ubuntu) has 2 kernel Image files.

```
# dpkg -L raspberrypi-kernel | grep "/boot/.*\.img"
/boot/kernel.img
/boot/kernel7.img
```

https://www.raspberrypi.org/documentation/configuration/config-txt/boot.md 
- kernel.img  (For Pi 1, Pi Zero)
--> "4.14.98+"
- kernel7.img  (For Pi 2, Pi 3)
--> "4.14.98-v7+"

When Boot it select, able to OS SDcard change to other Raspi.
But, I only use Raspberry Pi(1 B+),
```
# needrestart -b
NEEDRESTART-VER: 2.11
NEEDRESTART-KCUR: 4.14.98+
NEEDRESTART-KEXP: 4.14.98-v7+
NEEDRESTART-KSTA: 3
```

Then, I do "mv /boot/kernel7.img /boot/kernel7.img.unused", every kernel package update.
Can't do it better?
( /perl5/NeedRestart/Kernel/Linux.pm  nr_kernel_check_real )

**Comment by liske** [comment]
I don't think there is a generic way of filtering kernel images which are incompatible. It might be possible to add a configuration option for white or blacklisting kernel images.

**Comment by jplitza** [comment]
For the moment, one might want to install something like the following in `/etc/kernel/postinst.d/remove-unnecessary`:

```bash
#!/bin/sh

version="$1"
file="$2"

if [ -n "$file" ] && [ "$file" != "/boot/kernel.img" ]; then
  rm -f "$file"
fi
```

**Comment by takichikawa** [comment]
It is not the fault of this command. sorry.

I am sloth. :-)
In RaspberryPi, one SD card with Raspbian installed as MASTER can copy for multiple hardwares.
Then, for example, RaspberryPi ZeroW automatically uses "kernel.img", and RaspberryPi 3B + automatically uses "kernel7.img".

And when the 3B+ troubled, same SD card used by 3B+ can be boot as it is for ZeroW. 
but
```
 root@raspberrypi3p:~# needrestart -b
 NEEDRESTART-VER: 2.11
 NEEDRESTART-KCUR: 4.19.42-v7+
 NEEDRESTART-KEXP: 4.19.42-v7+
 NEEDRESTART-KSTA: 1
 root@raspberrypi3p:~#
```
boot same SD card.
```
 root@raspberrypi0w:~# needrestart -b
 NEEDRESTART-VER: 2.11
 NEEDRESTART-KCUR: 4.19.42+
 NEEDRESTART-KEXP: 4.19.42-v7+
 NEEDRESTART-KSTA: 3
 root@raspberrypi0w:~#
```

RaspberryPi / Raspbian may not ordinary . but
It is nice to be able to judge the kernel image depending on the environment occasion.


Another just amateur idea
` Linux.pm:  $iversion =~ s/-v7//s;
`
but also maybe "-v8" and future "-v9" ...


... not have to consider it.

**Comment by iandstanley** [comment]
This is still an issue as the default behaviour of needrestart is to put up a MODAL DIALOG box breaking automation scripts used in modern administration 

The error then occurs after every install if a package forcing the admin to sit in front of the screen and manually press enter after every single package install. 

It wouldn’t be such a problem if this was a rarely used script but it is a dependency on docker and some other big names in the Linux world


I would give a patch but I can’t get my head around Perl and would probably cause more damage than I fix. 

Could I suggest than before comparing the Kernel files you Just regex for only the kernel version number and drop off the -v* at the end 

Alternatively you could change the default behaviour to report to standard error and not dialog box

**Comment by licaon-kter** [comment]
Still and issue on RPi1
```
The currently running kernel version is 5.10.11+ which is not the expected kernel version 5.10.11-v7+. 
```

**Comment by Tuffiglig** [comment]
Other models as well.

Raspberry Pi Model B Rev 2 & Raspberry Pi Model B Plus Rev 1.2:
```
NEEDRESTART-KCUR: 5.10.11+
NEEDRESTART-KEXP: 5.10.11-v8+
```

Raspberry Pi 3 Model B Rev 1.2:
```
NEEDRESTART-KCUR: 5.10.11-v7+
NEEDRESTART-KEXP: 5.10.11-v8
```+

Raspberry Pi 4 Model B Rev 1.1:
```
NEEDRESTART-KCUR: 5.10.11-v7l+
NEEDRESTART-KEXP: 5.10.11-v8+
```

**Comment by licaon-kter** [comment]
@Tuffiglig yes and no, those could run the other kernel, but not on RPi1 ;)

**Comment by GRArmstrong** [comment]
> 
> 
> Still and issue on RPi1
> 
> ```
> The currently running kernel version is 5.10.11+ which is not the expected kernel version 5.10.11-v7+. 
> ```

Got this issue as well on my Pi 3b, I've just removed the `needrestart` package to get rid of the error. ¯\_(ツ)_/¯

**Comment by licaon-kter** [comment]
There's a config option that moves this to a warning line.

**Comment by llucax** [comment]
Any further details on how to fix this issue by changing a config file? Which config file is it? What should be added/removed/changed?

**Comment by licaon-kter** [comment]
`/etc/needrestart/needrestart.conf` uncomment and set `$nrconf {kernelhints} = -1`

**Comment by llucax** [comment]
Thanks. This is just a mitigation, right? You'll stop getting the false positives (warnings about a new kernel that is not really there) but you'll also start "getting" false negatives (never getting notified when a real new kernel was installed and a restart is really needed) or am I missing something?

**Comment by shutterfreak** [comment]
Ideally there would be a simple way to override the default kernel image checker code. On raspbian you could then ditch the '-v7+' / '-v8+' tail fragment of the kernel identifier.

**Comment by liske** [comment]
It should be possible to add some perl code to needrestart.conf on Raspian setting the filter accordingly. Since it is Raspian specific it is not part of the upstream config.
