### ISSUE TITLE
Service php7.0-fpm fail to restart

### ISSUE THREAD

**Issue by re-vax** [liske/needrestart#151]
I've a running php-fpm service on debian 9. After upgrade, the service need to be restarted.

The problem is the service name is not well recognized:

```
Restarting services using systemd...
Failed to restart 0-fpm.service: Unit 0-fpm.service not found.
```

```
service php7.0-fpm status
● php7.0-fpm.service - The PHP 7.0 FastCGI Process Manager

```
It seems that the service name is truncated:  **0-fpm.service** instead of **php7.0-fpm.service**

**Comment by liske** [comment]
Which version of needresrtart did you use? Please give needrestart from stretch-backports a try if you did not use it, yet. Can you please provide the output of `/proc/$PID/cgroup` (where $PID is the pid of one of the php fpm processes)?
