### ISSUE TITLE
Kernel version false positive on Pi 4

### ISSUE THREAD

**Issue by fenhl** [liske/needrestart#155]
I get the following message on the Raspberry Pi 4:

> The currently running kernel version is 4.19.58-v7l+ which is not the expected kernel version 4.19.58-v7+.

The message persists after rebooting.

**Comment by liske** [comment]
This is related to #146: Raspbian is shiping different kernel images to support different Raspberry Pi board variants.

**Comment by git-developer** [comment]
This problem also occurs on a Raspberry Pi 3 with current Raspbian Buster. On a fresh installation of Buster, the boot partition is bigger than on previous releases (e.g. Stretch or Jessie) and contains additional kernel files:
```
kernel.img
kernel7.img
kernel7l.img
kernel8.img
```
`kernel7.img` (e.g. `4.19.75-v7+`) is 32-Bit (`armv7l`) and used by default; `kernel8.img` (e.g. `4.19.75-v8+`) is 64-Bit (`aarch64`). On my installation, the 64-Bit kernel causes random freezes, so I'd like to avoid it. A white- and/or blacklist as [suggested by @liske](https://github.com/liske/needrestart/issues/146#issuecomment-482797604) would be great.
