### ISSUE TITLE
Microcode check error on Ubuntu 18.04

### ISSUE THREAD

**Issue by XOmniverse** [liske/needrestart#156]
On Ubuntu 18.04 on a DigitalOcean droplet, there appears to be an issue with the microcode check failing. 

> Processor microcode update         
> 
> The currently running processor microcode revision is 0x1 which is not the expected microcode revision 0x5000021. 
> 
> Restarting the system to load the new processor microcode will not be handled automatically, so you should consider rebooting.

I can duplicate this error with the needrestart -w command. For reference, this is the CPU being used:

Model name:          Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz

**Comment by liske** [comment]
Could you provide the output of `needrestart -v`?
