### ISSUE TITLE
Needrestart constantly expects a reboot with Tomcat 9 / OpenJDK

### ISSUE THREAD

**Issue by gsbab** [liske/needrestart#157]
Hello,

We have Tomcat 9 in use with OpenJDK 8 on a Debian Server 9. Recently, needrestart seems to expect a reboot for tomcat, although it has been restarted several times. The system was also completely restarted.

Needrestart v3.4:

```
# needrestart -vr l
[main] eval /etc/needrestart/needrestart.conf
[main] needrestart v3.4
[main] running in root mode
[Core] Using UI 'NeedRestart::UI::stdio'...
[main] systemd detected
[main] vm detected
[Core] #16088 is a NeedRestart::Interp::Java
[Core] #16088 uses obsolete script file(s):
[Core] #16088  /opt/apache-tomcat-9.0.20/temp/ehcache-sizeof-agent937301964612326002.jar
[main] #16088 is not a child
[Core] #22739 is a NeedRestart::Interp::Perl
[Perl] #22739: source=/etc/apache2/scripts/apache_filter_log.pl
[Core] #22740 is a NeedRestart::Interp::Perl
[Perl] #22740: source=/etc/apache2/scripts/apache_filter_log.pl
[Perl] #22740: use cached file list
[Core] #22741 is a NeedRestart::Interp::Perl
[Perl] #22741: source=/etc/apache2/scripts/apache_filter_log.pl
[Perl] #22741: use cached file list
[main] #16088 exe => /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
[Core] #16088 is a NeedRestart::Interp::Java
[Core] #16088 source is UNKNOWN
[main] #16088 is tomcat.service
[main] inside container or vm, skipping microcode checks
[Kernel] Linux: kernel release 4.9.0-9-amd64, kernel version #1 SMP Debian 4.9.168-1+deb9u4 (2019-07-19)
[Kernel/Linux] /boot/vmlinuz-4.9.0-9-amd64 => 4.9.0-9-amd64 (debian-kernel@lists.debian.org) #1 SMP Debian 4.9.168-1+deb9u4 (2019-07-19) [4.9.0-9-amd64]*
[Kernel/Linux] /boot/vmlinuz-3.16.0-9-amd64 => 3.16.0-9-amd64 (debian-kernel@lists.debian.org) #1 SMP Debian 3.16.68-1 (2019-05-22) [3.16.0-9-amd64]
[Kernel/Linux] /boot/vmlinuz-3.16.0-8-amd64 => 3.16.0-8-amd64 (debian-kernel@lists.debian.org) #1 SMP Debian 3.16.64-2 (2019-04-01) [3.16.0-8-amd64]
[Kernel/Linux] /boot/vmlinuz-3.16.0-4-amd64 => 3.16.0-4-amd64 (debian-kernel@lists.debian.org) #1 SMP Debian 3.16.51-3 (2017-12-13) [3.16.0-4-amd64]
[Kernel/Linux] Expected linux version: 4.9.0-9-amd64

Running kernel seems to be up-to-date.

Services to be restarted:
 systemctl restart tomcat.service

No containers need to be restarted.

No user sessions are running outdated binaries.
```
```
# grep -i ehcache /proc/16088/maps 
7f9b24feb000-7f9b24fec000 r--s 00000000 fe:02 21498936                   /opt/apache-tomcat-9.0.20/temp/ehcache-sizeof-agent937301964612326002.jar
```

**Comment by liske** [comment]
You need to change needrestart's config to ignore those temporary files in `/opt/apache-tomcat-9.0.20/temp/`:

```
push(@{$nrconf{blacklist_mappings}}, qr(^/opt/apache-tomcat-[\d.]+/temp/));
```

**Comment by idl0r** [comment]
Well, that file isn't marked as being deleted / still in use, so why is it shown anyway? Isn't that a false-positive?

**Comment by liske** [comment]
In case of software updates using removed stuff might indicate that a restart is pending.

**Comment by valerio-bozzolan** [comment]
Sorry for necroposting :)

I believe the root problem is not about temporary files, but is that we should consider `tomcat.service` as a critical service as default, to be not auto-restarted. This has sense if we look at Docker, libvirt, and other critical services which are already listed in that way.

When a `tomcat.service` is installed in a server (frequently `tomcat.service` or `tomcat10.service` or `tomcat-acmecustomer.service` etc), very much probably that Tomcat is one of the most delicate and critical services, with potentially long-running Java schedulers. Java is a beast which is often used in legacy banking or tax or other critical contexts, and there, uptime and pretty much scheduled manual maintenance is everything.

If the maintainer thinks "uhm maybe", then I can suggest this new line:

https://github.com/liske/needrestart/blob/master/ex/needrestart.conf

```
$nrconf{override_rc} = {
    # do not restart Tomcat as it may cause critical downtimes
    qr(^tomcat) => 0,
};
```

Thanks again :)
