### ISSUE TITLE
Integrate with dynamic MOTD on Ubuntu

### ISSUE THREAD

**Issue by bartmichu** [liske/needrestart#164]
Current versions of Ubuntu are generating MOTD dynamically, populating it with information about awaiting updates and system restart (among others).
I think it would make sense to add a list of daemons that need to be restarted - or maybe just a number of daemons (if any).

**Comment by liske** [comment]
This is not related to upstream. Ubuntu specific stuff needs to be added by Ubuntu maintainers so you should consider to open the bug there.
