### ISSUE TITLE
needrestart flooding desktop with dozens of libnotify messages daily

### ISSUE THREAD

**Issue by scruloose** [liske/needrestart#174]
I'm using `needrestart` in conjunction with `unattended-upgrades` to keep a couple of desktop workstations up to date, which mostly works very smoothly.

One problem I have, though, is that `needrestart` routinely generates *far too many* `libnotify` messages. I don't know whether `needrestart` is firing its `libnotify` script once for every package that's been upgraded or what, but every day when `unattended-upgrades` runs, `needrestart` cranks out a whole stack of duplicate `libnotify` messages. Some days it's ten or so, some days it's 50 or so, and on any given day all of them seem to be the same message listing the same services over and over again.

Given that they are all "critical" urgency messages, this is highly intrusive, forcing me to stop what I'm doing to click away all these notifications or else have my entire desktop buried as they stack up.

Do I have something configured wrong, or is `needrestart` lacking a mechanism to notice that it has just notified the user about a given upgrade and thus doesn't need to notify again (and again) about the same thing...?

**Comment by liske** [comment]
`needrestart` should trigger a single notification for each session (see also `/etc/needrestart/notify.d/400-notify-send`). Could you provide the output of `needrestart -v`?

**Comment by scruloose** [comment]
When I invoke `needrestart` directly, it seems to work as expected. Likewise when I invoke `apt upgrade` manually, it seems to work as expected, delivering one notification regardless of how many packages are upgraded and how many services need restarting.

It's specifically when `unattended-upgrades` runs that I get a bunch of duplicate notifications. I haven't dug into the code to verify this, but I have a suspicion that `unattended-upgrades` is invoking `apt` separately for each package it upgrades rather than issuing a single `apt upgrade` command. I suspect this partly because `unattended-upgrades` config allows control over which packages get upgraded and which get excluded from the automatic upgrades, and this mechanism seems to be internal to `unattended-upgrades` itself, separate from `apt`'s held packages and pinning and so on. Does that make sense?

And here is the output I get from `needrestart -v`

[needrestart.txt](https://github.com/liske/needrestart/files/4211293/needrestart.txt)

**Comment by NICHOLAS85** [comment]
Do you run unattended-upgrades with `MinimalSteps` mode enabled? If so it's true that apt is being invoked repeatedly, and this could be the cause of Needrestart flooding your notifications. Heres a related bug report I could find: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=911765

**Comment by liske** [comment]
It seems not to be a bug of needrestart nor do I have any idea howto workaround this behavior of *unattended-upgrades*.
