### ISSUE TITLE
Files in conf.d: override or expand needrestart.conf ?

### ISSUE THREAD

**Issue by martux69** [liske/needrestart#184]
Hi,

I have question regarding files in the conf.d directory:
I would like to leave the needrestart.conf unchanged and append additional regex for a blacklist variable in a separate file in the conf.d folder, e.g. expand $nrconf{blacklist_interp} with qr(^/export/home/):
```
cat ppi-blacklist.conf
$nrconf{blacklist_interp} = [
       # ignore temporary files
      qr(^/export/home/),
];
```

Will this work in addition or must I repeat the other entries for $nrconf{blacklist_interp} from needrestart.conf ?

Kind regards
Martin

**Comment by liske** [comment]
This would replace the list of `blacklist_interp`. It should work like this:

```
push(@{ $nrconf{blacklist_interp} }, qr(^/export/home/));
```

**Comment by liske** [comment]
Closing since it seems to be resolved.
