### ISSUE TITLE
False positives for java processes

### ISSUE THREAD

**Issue by izaera** [liske/needrestart#185]
I'm experiencing false positives with `java` processes that seem to use temporary files.

My platform is Arch Linux and I'm using Oracle JDK 1.8.0_251.

My hypothesis is that some API is creating temporary files and immediately deleting them to avoid leaving them hanging around, because I'm seeing the following output from `needrestart`:

```shell
$ needrestart -v
[main] eval /etc/needrestart/needrestart.conf
[main] needrestart v3.5
[main] running in user mode
[Core] Using UI 'NeedRestart::UI::stdio'...
[main] systemd detected
[Core] #4803 is a NeedRestart::Interp::Python
[Python] #4803: source=/usr/bin/chrome-gnome-shell
[main] #16676 uses deleted /home/ivan/.cache/JetBrains/IntelliJIdea2020.1/tmp/jna4214035373404461359.tmp
[main] #22353 uses deleted /home/ivan/Liferay/CE/bundles/osgi/state/org.eclipse.osgi/162/data/elasticSearch-tmpDir/jna3624712770618623498.tmp
Your outdated processes:
java[22353, 16676]
```

I would like to narrow the error a bit more, but I have never used Perl, so I have no idea how to debug it :-(.

**Comment by koocotte** [comment]
I had the same problem with openhab2.

You can configure needrestard to ignore filepath based on regex in /etc/needrestart/conf.d/

I set needrestart to ignore files in the /var/lib/openhab2/.cache/JNA/ directory :
/etc/needrestart/conf.d/ignore-openhab2.conf 
```
# Ignore openhab2 temporary file
push @{$nrconf{blacklist_mappings}}, qr#^/var/lib/openhab2/.cache/JNA/#;
```

**Comment by fpoulain** [comment]
Similar problem on java process for Jitsi Video Bridge : https://github.com/jitsi/jitsi-videobridge/issues/1166

Solved with
```
$nrconf{blacklist_mappings} = [
[…]
    # Videobridge
    qr(^/tmp/jna-),
```
in `/etc/needrestart/needrestart.conf`.
