### ISSUE TITLE
Exclusion candidates: VMWare

### ISSUE THREAD

**Issue by stdedos** [liske/needrestart#190]
I don't know which of the following services

```
│    [ ] vmware.service                       │ 
│    [ ] vmware-USBArbitrator.service         │ 
│    [ ] vmware-workstation-server.service    │
```

are unsafe to restart while a VM is running and I think at least one of them, if restarted, leads to destroyed state of the started guests.

For safety sake, can they all be blacklisted?

**Comment by liske** [comment]
Feel free to add it to your local configuration but I do not like to add this upstream since it is proprietary software.
