### ISSUE TITLE
debconf warnings on Fedora

### ISSUE THREAD

**Issue by bdaase** [liske/needrestart#192]
I recently noticed, that needrestart (tested versions 3.4 and 3.5) warns about debconf stuff on Fedora 32/33:

```
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/vendor_perl/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
```

Why would that even make sense to have debconf running on an rpm based system?

It also seems like Fedora package maintainers stripe out some debconf things when [packaging it downstream](https://koji.fedoraproject.org/koji/buildinfo?buildID=1517210).

**Comment by duck-rh** [comment]
Debconf is used when you run it interactively to ask you questions. Now this has been made optional in the package and you can set `$nrconf{ui}` to disable it if you wish.

I guess a dependency is missing on debconf's side to at least recommend whiptail or dialog, thus this warning.

As for the debconf templates, I had difficulties generating them properly in the past and I'm simply using the generated result in the Debian package, so nothing is striped out or altered in any way. I think it was a problem with po-debconf in Fedora but I don't clearly recall; it may not be necessary and I'll check next time.

**Comment by liske** [comment]
> Debconf is used when you run it interactively to ask you questions. Now this has been made optional in the package and you can set `$nrconf{ui}` to disable it if you wish.

Maybe there should be no debconf dependency/recommend on non-debian distributions or a dependency for a "dialog-like program" is required, too.

**Comment by liske** [comment]
I'm closing this issue since it is a packaging issue of debconf on Fedora, isn't it?
