### ISSUE TITLE
False positives (chromium, cinnamon, electron) when using NVIDIA drivers on Arch

### ISSUE THREAD

**Issue by starquake** [liske/needrestart#198]
I did not update anything, but with nvidia drivers installed it says some services need updating, even immediately after boot. Any idea? Help to debug is appreciated.

When I run needrestart while using nouveau there are no services that need restarting. When I use nvidia drivers it reports "User sessions running outdated binaries".

A typical example:
```User sessions running outdated binaries:
 starquake @ session #3: chromium[1292,1317], cinnamon-launch[1161]
 starquake @ user manager service: electron[3241]
```
Running it with verbose:
```
[main] eval /etc/needrestart/needrestart.conf
[main] needrestart v3.5
[main] running in user mode
[Core] Using UI 'NeedRestart::UI::stdio'...
[main] systemd detected
[Core] #1161 is a NeedRestart::Interp::Python
[Python] #1161: source file not found, skipping
[Python] #1161:  reduced ARGV:                          
[main] #1164 uses deleted /memfd:/.glXXXXXX
[Core] #1240 is a NeedRestart::Interp::Python
[Python] #1240: source file not found, skipping
[Python] #1240:  reduced ARGV:                          
[Core] #1269 is a NeedRestart::Interp::Python
[Python] #1269: source file not found, skipping
[Python] #1269:  reduced ARGV:                          
[Core] #1286 is a NeedRestart::Interp::Python
[Python] #1286: source=/usr/share/system-config-printer/applet.py
[main] #1317 uses deleted /memfd:/.glXXXXXX
[main] #1333 uses deleted /memfd:/.glXXXXXX
[Core] #1731 is a NeedRestart::Interp::Python
[Python] #1731: source=/usr/bin/powerline-daemon
[main] #3271 uses deleted /memfd:/.glXXXXXX
Your outdated processes:
chromium[1333, 1317], cinnamon[1164], electron[3271]
```

Arch Kernel version: `5.9.6-arch1-1`
NVIDIA version: `455.38`
Chromium version: `86.0.4240.183`

**Comment by liske** [comment]
It looks like we need to put this weirrd `/memfd:/.glXXXXXX` mapping to the *blacklist_mappings* config option.

**Comment by starquake** [comment]
I can test this if you want. How would I do that?

**Comment by starquake** [comment]
I created the file `/etc/needrestart/conf.d/ignore-memfd-gl.conf` with contents:
```
push @{$nrconf{blacklist_mappings}}, qr#^/memfd:/.glXXXXXX#;
```
And that seems to help.

**Comment by liske** [comment]
This looks good - feel free to file a PR updating `ex/needrestart.conf` if you like.

**Comment by brettinternet** [comment]
@starquake Thank you for this fix and thank you @liske for your great work on this library. Is there any additional testing required before merging #200?

**Comment by liske** [comment]
Just a minor issue with the chosen quoting character (hashes vs. braces). I prefer to use the same characters in the default config.

**Comment by liske** [comment]
Thanks for your contribution @starquake !
