### ISSUE TITLE
needrestart list mode not working as expected

### ISSUE THREAD

**Issue by daniejstriata** [liske/needrestart#202]
I use remote execution to run` apt update; apt upgrade -yy` on all my Debian 10 servers. I quickly released that I will have to configure `needrestart` to list updates rather than bring up its normal menu.

I uncommented the nrconf entry in /etc/needrestart/needrestart.conf
`$nrconf{restart} = 'l';`
expecting to see a list when I run `needrestart` but it still shows the menu. 

How do I get needrestart to only list after apt updates services that needs to be restarted? What language is being used for the config file? I don't see a guide how the configuration of needrestart works.

**Comment by liske** [comment]
This is triggered by the debconf frontend. Maybe you could:

- suspend needrstart by setting the [`NEEDRESTART_SUSPEND`](https://manpages.debian.org/buster/needrestart/needrestart.1.en.html#ENVIRONMENT) env variable
- change the debconf frontend by setting [`DEBIAN_FRONTEND`](https://manpages.debian.org/buster/debconf-doc/debconf.7.en.html#Frontends) to `noninteractive` (be aware that it may also affect package configuration dialogs)
- do not allocate a TTY (`ssh -T ...`)
