### ISSUE TITLE
Wrong selection of ssh service restart

### ISSUE THREAD

**Issue by baruchsiach** [liske/needrestart#203]
When ssh client session multiplexing feature is used (ControlMaster configuration option), needrestart confuses the mux control process with the entirely unrelated local ssh server.

Here is the relevant part from needrestart verbose output:

```
[main] #113703 uses deleted /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
[main] #113703 is not a child
...
[main] #113703 exe => /usr/bin/ssh
[main] trying systemctl status
[main] #113703 running /etc/needrestart/hook.d/10-dpkg
[main] #113703 package: openssh-client
[main] #113703 running /etc/needrestart/hook.d/20-rpm
[main] #113703 running /etc/needrestart/hook.d/30-pacman
[main] #113703 running /etc/needrestart/hook.d/90-none
[main] #113703 package: ssh
[main] no pidfile reference found at ssh
...
Restart «ssh»? [Ynas?] n
...
Service restarts being deferred:
...
 systemctl restart ssh.service
```

PID 113703 shows in `ps ax` output as follows:

```
 113703 ?        Ss     0:05 ssh: <socket_path> [mux]
```

It looks like the source of confusion is the process name `ssh` that is the same as sshd service name for systemd.

On my system (Debian testing) the openssh-server package is installed, but the ssh service is disabled. So I found the issue when I found sshd running when it was supposed to be disabled. Turned out that needrestart started sshd.

The Debian `ssh` metapackage is not installed here.

**Comment by liske** [comment]
Could you please provide the output of `/proc/$PID/cgroup` for the master ssh?

**Comment by baruchsiach** [comment]
> Could you please provide the output of `/proc/$PID/cgroup` for the master ssh?

```
$ ps ax|grep ssh
  15072 ?        Ss     0:01 <socket_path> [mux]
$ cat /proc/15072/cgroup
0::/user.slice/user-1000.slice/session-2.scope
$ id -u
1000
```

**Comment by liske** [comment]
This looks like related to #235: needrestart 3.5 is not cgroup v2 aware and fails to detect this as a user session
