### ISSUE TITLE
Some process issues

### ISSUE THREAD

**Issue by HumanG33k** [liske/needrestart#205]
Hello,

I currently make test with debian testing.

I find issues with :
- mpd (music player deamon) look like is always ask for a restart pretty sure not always needed.
- elogind is check and it close users session it should have the same behavior as dbus sddm and so on.
- connman currently not restart even check (maybe a bad configuration on my side) i have to service connman restart to restart it.

I not use systemd.
tell me if you need more information.

**Comment by liske** [comment]
I've changed the default configuration to not restart `elogind` by default. Could you please provide the output of `needrestart -v` for the other issues?

**Comment by liske** [comment]
Closing due to missing feedback. Feel free to reopen if issue still exists / more info is available.
