### ISSUE TITLE
Debian Epyc microcode

### ISSUE THREAD

**Issue by Motophan** [liske/needrestart#210]
[main] eval /etc/needrestart/needrestart.conf
[main] needrestart v3.4
[main] running in root mode
[Core] Using UI 'NeedRestart::UI::stdio'...
[main] systemd detected
[main] #1 uses deleted /usr/lib/x86_64-linux-gnu/libudev.so.1.6.13
[main] #1 is not a child
[main] #2371 uses deleted /usr/lib/x86_64-linux-gnu/libnss_systemd.so.2
[main] #2371 is not a child
[main] #2382 uses obsolete binary /usr/lib/systemd/systemd-logind
[main] #2382 is not a child
[main] #2415 uses deleted /usr/lib/x86_64-linux-gnu/libnss_systemd.so.2
[main] #2415 is not a child
[main] #2436 uses obsolete binary /usr/bin/python3.7
[main] #2436 is not a child
[main] #4933 uses obsolete /usr/lib/plexmediaserver/Plex Transcoder2
[docker] #4933 is part of docker container '41531d5783e6da868a7059eae3ee3428630cfab155ee6c9756e0d3defe76faf2' and will be ignored
[main] #6655 uses deleted /usr/lib/x86_64-linux-gnu/libudev.so.1.6.13
[main] #6655 is a child of #6654
[Core] #19611 is a NeedRestart::Interp::Python
[Python] #19611: could not get current working directory, skipping
[Core] #20592 is a NeedRestart::Interp::Python
[Python] #20592: could not get current working directory, skipping
[Core] #21339 is a NeedRestart::Interp::Java
[Core] #21385 is a NeedRestart::Interp::Python
[Python] #21385: could not get current working directory, skipping
[Core] #21746 is a NeedRestart::Interp::Python
[Python] #21746: could not get current working directory, skipping
[Core] #28989 is a NeedRestart::Interp::Python
[Python] #28989: process cwd is unreachable
[Core] #30610 is a NeedRestart::Interp::Java
[main] #31725 uses obsolete /app/Jackett/libSystem.IO.Compression.Native.so
[docker] #31725 is part of docker container '77191f26848be0f2d481d24e788e7c309e44af53e363a79d0012ad1502357646' and will be ignored
[main] #1 exe => /usr/lib/systemd/systemd
[main] #1 unexpected cgroup '/init.scope'
[main] trying systemctl status
[main] #1 running /etc/needrestart/hook.d/10-dpkg
dpkg-query: no path found matching pattern /usr/lib/systemd/systemd
[main] #1 running /etc/needrestart/hook.d/20-rpm
[main] #1 running /etc/needrestart/hook.d/90-none
[main] #2371 exe => /usr/bin/dbus-daemon
[main] #2371 is dbus.service
[main] #2382 exe => /usr/lib/systemd/systemd-logind
[main] #2382 is systemd-logind.service
[main] #2415 exe => /usr/bin/dockerd
[main] #2415 is docker.service
[main] #2436 exe => /usr/bin/python3.7
[Core] #2436 is a NeedRestart::Interp::Python
[Core] #2436 source is /usr/share/unattended-upgrades/unattended-upgrade-shutdown
[main] #2436 is unattended-upgrades.service
[main] #6654 exe => /usr/lib/systemd/systemd
[main] #6654 part of user manager service: uid=1001
[uCode/Intel] current revision: 0x8001250
+ iucode_tool --scan-system
+ grep -oE [^[:space:]]+$
+ sig=processor
+ [ -r /sys/devices/system/cpu/cpu0/microcode/processor_flags ]
+ cat /sys/devices/system/cpu/cpu0/microcode/processor_flags
+ filter=-s processor,0x0
+ type bsdtar
+ IUCODE_TOOL_EXTRA_OPTIONS=
+ test -r /etc/default/intel-microcode
+ test  = no
+ [ -r /usr/share/misc/intel-microcode* ]
+ iucode_tool -l -s processor,0x0 --ignore-broken -tb /lib/firmware/intel-ucode
+ grep processor
[uCode/Intel] did not get available microcode version
[Kernel] Linux: kernel release 4.19.0-14-amd64, kernel version #1 SMP Debian 4.19.171-2 (2021-01-30)
[Kernel/Linux] /boot/vmlinuz-4.19.0-16-amd64 => 4.19.0-16-amd64 (debian-kernel@lists.debian.org) #1 SMP Debian 4.19.181-1 (2021-03-19) [4.19.0-16-amd64]
[Kernel/Linux] /boot/vmlinuz-4.19.0-14-amd64 => 4.19.0-14-amd64 (debian-kernel@lists.debian.org) #1 SMP Debian 4.19.171-2 (2021-01-30) [4.19.0-14-amd64]*
[Kernel/Linux] Expected linux version: 4.19.0-16-amd64

Pending kernel upgrade!

Running kernel version:
  4.19.0-14-amd64

Diagnostics:
  The currently running kernel version is not the expected kernel version 4.19.0-16-amd64.

Restarting the system to load the new kernel will not be handled automatically, so you should consider rebooting. [Return]

**Comment by Motophan** [comment]
[main] eval /etc/needrestart/needrestart.conf
[main] needrestart v3.4
[main] running in root mode
[Core] Using UI 'NeedRestart::UI::stdio'...
[main] systemd detected
[Core] #2172 is a NeedRestart::Interp::Python
[Python] #2172: source=/usr/share/unattended-upgrades/unattended-upgrade-shutdown
[Core] #4814 is a NeedRestart::Interp::Python
[Python] #4814: could not get current working directory, skipping
[Core] #5570 is a NeedRestart::Interp::Python
[Python] #5570: could not get current working directory, skipping
[Core] #7463 is a NeedRestart::Interp::Python
[Python] #7463: could not get current working directory, skipping
[Core] #7766 is a NeedRestart::Interp::Python
[Python] #7766: could not get current working directory, skipping
[Core] #8044 is a NeedRestart::Interp::Java
[Core] #9131 is a NeedRestart::Interp::Java
[main] #10017 uses obsolete /app/Jackett/jackett
[docker] #10017 is part of docker container 'a0bbc5a03f66b58a2e499965c137ed6a6f613a0d6160afce54a34e5a30e25b85' and will be ignored
[uCode/Intel] current revision: 0x8001250
+ + grepiucode_tool -oE [^[:space:]]+$ --scan-system

+ sig=processor
+ [ -r /sys/devices/system/cpu/cpu0/microcode/processor_flags ]
+ cat /sys/devices/system/cpu/cpu0/microcode/processor_flags
+ filter=-s processor,0x0
+ type bsdtar
+ IUCODE_TOOL_EXTRA_OPTIONS=
+ test -r /etc/default/intel-microcode
+ test  = no
+ [ -r /usr/share/misc/intel-microcode* ]
+ iucode_tool -l -s processor,0x0 --ignore-broken -tb /lib/firmware/intel-ucode
+ grep processor
[uCode/Intel] did not get available microcode version
[Kernel] Linux: kernel release 4.19.0-16-amd64, kernel version #1 SMP Debian 4.19.181-1 (2021-03-19)
[Kernel/Linux] /boot/vmlinuz-4.19.0-16-amd64 => 4.19.0-16-amd64 (debian-kernel@lists.debian.org) #1 SMP Debian 4.19.181-1 (2021-03-19) [4.19.0-16-amd64]*
[Kernel/Linux] /boot/vmlinuz-4.19.0-14-amd64 => 4.19.0-14-amd64 (debian-kernel@lists.debian.org) #1 SMP Debian 4.19.171-2 (2021-01-30) [4.19.0-14-amd64]
[Kernel/Linux] Expected linux version: 4.19.0-16-amd64

Running kernel seems to be up-to-date.

Failed to check for processor microcode upgrades.

No services need to be restarted.

No containers need to be restarted.

No user sessions are running outdated binaries.

**Comment by liske** [comment]
Support to AMD ucode has been added to needrestart 3.5+.
