### ISSUE TITLE
needrestart seems to no longer show individual processes

### ISSUE THREAD

**Issue by calestyo** [liske/needrestart#213]
Hey.

Since a while it seems that needrestart no longer shows me any individual processes that run with outdated binaries like libs... instead I only get a reference to `user@1000.service` being outdated (which kills  however everything).

```
# needrestart -v
[main] eval /etc/needrestart/needrestart.conf
[main] needrestart v3.5
[main] running in root mode
[Core] Using UI 'NeedRestart::UI::stdio'...
[main] systemd detected
[main] #2626 uses deleted /lib/x86_64-linux-gnu/libfuse3.so.3.10.2
[main] #2626 is a child of #2546
[Core] #2840 is a NeedRestart::Interp::Python
[Python] #2840: source file not found, skipping
[Python] #2840:  reduced ARGV:                          
[Core] #2865 is a NeedRestart::Interp::Python
[Python] #2865: source=/usr/share/smart-notifier/smart-notifier
[Core] #2867 is a NeedRestart::Interp::Python
[Python] #2867: source file not found, skipping
[Python] #2867:  reduced ARGV:                          
[Core] #2975 is a NeedRestart::Interp::Python
[Python] #2975: source file not found, skipping
[Python] #2975:  reduced ARGV:                          
[Core] #3058 is a NeedRestart::Interp::Python
[Python] #3058: source=/usr/bin/virt-manager
[Core] #3074 is a NeedRestart::Interp::Python
[Python] #3074: source=/usr/share/system-config-printer/applet.py
[main] #3331 uses obsolete binary /bin/fusermount3
[main] #3331 is a child of #3323
[main] #2546 exe => /lib/systemd/systemd
[main] trying systemctl status
[main] #2546 is user@1000.service
[main] #3323 exe => /usr/libexec/xdg-document-portal
[main] trying systemctl status
[main] #3323 is user@1000.service
[ucode] using NeedRestart::uCode::AMD
[ucode] using NeedRestart::uCode::Intel
[uCode/AMD] #0 cpu vendor id mismatch
[uCode/Intel] #0 current revision: 0x00de
+ iucode_tool --scan-system
+ grep -oE [^[:space:]]+$
+ sig=0x000806e9
+ [ -r /sys/devices/system/cpu/cpu0/microcode/processor_flags ]
+ cat /sys/devices/system/cpu/cpu0/microcode/processor_flags
+ filter=-s 0x000806e9,0x80
+ test -r /etc/needrestart/iucode.sh
+ . /etc/needrestart/iucode.sh
+ type bsdtar
+ imgfiles=
+ [ -r /boot/intel-ucode.img ]
+ [ -r /boot/early_ucode.cpio ]
+ [ -n  ]
+ IUCODE_TOOL_EXTRA_OPTIONS=
+ test -r /etc/default/intel-microcode
+ . /etc/default/intel-microcode
+ test  = no
+ [ -r /usr/share/misc/intel-microcode* ]
+ iucode_tool -l -s 0x000806e9,0x80 --ignore-broken -tb /lib/firmware/intel-ucode
+ grep 0x000806e9
[uCode/Intel] #0 available revision: 0x00de
[Kernel] Linux: kernel release 5.10.0-6-amd64, kernel version #1 SMP Debian 5.10.28-1 (2021-04-09)
[Kernel/Linux] /boot/vmlinuz-5.10.0-6-amd64 => 5.10.0-6-amd64 (debian-kernel@lists.debian.org) #1 SMP Debian 5.10.28-1 (2021-04-09) [5.10.0-6-amd64]*
[Kernel/Linux] Expected linux version: 5.10.0-6-amd64

Running kernel seems to be up-to-date.

The processor microcode seems to be up-to-date.

Restarting services...
Services to be restarted:
```

Doesn't that  make it quite useless? And is there a way to not fold all these things into the user session?

Cheers,
Chris.

**Comment by kescherCode** [comment]
No, the notification is quite right. user@1000.service is referring to the systemd user session.
A common thing to try manually is (as root):

```
systemctl stop user@<uid>.service
systemctl daemon-reexec
systemctl start user@<uid>.service
```

**Comment by calestyo** [comment]
Well sure,... but that's typically useless: it's the same as if you simply say every time: just restart your machine.

What would be useful however is, if one was told the exact processes which use outdated libraries/etc. - as it used to be done - and not hiding those behind the user session.

**Comment by kescherCode** [comment]
It's not really the same as being told to restart the entire machine, that's for sure.

But yes, perhaps for user sessions, the exact processes that has these user sessions ask for a restart should be listed along with the choice prompt for clarity.

**Comment by mlmatlock** [comment]
Here's my work-around for the lack of detail for user@1000.service:

1.  Answer no to restart the user session.
2. Get a list of what is remaining:

`sudo lsof / | egrep -w DEL\|deleted`

You should be able to determine from the output which user services you can restart, instead of restarting the entire session.

**Comment by calestyo** [comment]
> It's not really the same as being told to restart the entire machine, that's for sure.

Well I think effectively it is - at least for any non-services processes.

needrestart used to tell me on the command line and via some GUI popup which (user) processes exactly were using outdated libraries/etc.
It no longer does so since a while, but rather hides anything behind the user@<id>.service.

But this doesn't really give much valuable information - it just tells there is something or there is nothing at all. No easy way - as there earlier - to then act and restart the processes as one likes.

What @mlmatlock suggests is also just doing it manually again.

**Comment by calestyo** [comment]
Especially, this used to work already. I got popups an some output on the console where it told e.g. bash with some PID is outdated.

**Comment by liske** [comment]
This is a regression triggered by a changed cgroup naming schema (due to cgroups v2). Needrestart does *not* identify that `user@1000.service` is a user session so it handles it like a daemon.

**Comment by liske** [comment]
cc #235

**Comment by pabs3** [comment]
The Debian bug about this:

https://bugs.debian.org/1005953

**Comment by calestyo** [comment]
Thx for fixing!
