### ISSUE TITLE
differ if microcode can not be checked due to missing components or unsupported plattform (i.e. ARM)

### ISSUE THREAD

**Issue by Wiggum127** [liske/needrestart#220]
I always get "Failed to check for processor microcode upgrades" at the end of every apt-get upgrade on my Raspbian (Debian Buster) on a RPI 2B. Currently running 5.10.63-v7+ armv7l.

Is there anything I can add to help find the root cause of this?

Thanks.

**Comment by mmitch** [comment]
I'm no developer here, but just have looked over exactly that part of the code:

Microcode updates can currently only be detected for Intel and AMD cpus (see [README.uCode.md](https://github.com/liske/needrestart/blob/e6176258e6b9f9f907736cbe1f8d148582a057d9/README.uCode.md)).
The Raspberry 2B runs on a Broadcom ARM chip, which currently is not supported.

**Comment by liske** [comment]
Yes there is no implementation for ARM.

**Comment by Wiggum127** [comment]
If that's the case, just tell the user there is no implementation for his CPU, instead of the misleading "Failed to check for processor microcode upgrades". This makes the user think he's done something wrong or there is a configuration error on his system/network. Just state "This CPU is not supported"

**Comment by liske** [comment]
I'll keep this as a wishlist issue. The current implementation lacks the ability to differ why microcode checks are not possible.
