### ISSUE TITLE
false positive Postfix in LXC containers

### ISSUE THREAD

**Issue by lpirl** [liske/needrestart#23]
I run a pretty much standard Debian testing on a LXC host and in its LXC containers.
Running `needrestart`(from Debian repositories or from Git HEAD) on the host, always detects all LXC containers and Postfix to be restarted, even after a fresh reboot.
`needrestart.conf` is at its defaults.

    ./needrestart -vvvvklrl
    [main] eval /etc/needrestart/needrestart.conf
    [main] running in root-mode
    [Core] Using UI 'NeedRestart::UI::stdio'...
    [main] detected systemd
    [main] #1770 uses obsolete /usr/lib/postfix/sbin/pickup
    [LXC] #1770 is part of LXC container 'baz_container/system.slice/postfix.service' and should be restarted
    [main] #2400 uses obsolete /usr/lib/postfix/sbin/pickup
    [LXC] #2400 is part of LXC container 'foo_container/system.slice/postfix.service' and should be restarted
    [main] #2404 uses obsolete /usr/lib/postfix/sbin/tlsmgr
    [LXC] #2404 is part of LXC container 'foo_container/system.slice/postfix.service' and should be restarted
    [Core] #2458 is a NeedRestart::Interp::Python
    Use of uninitialized value in chdir at /usr/share/perl5/NeedRestart/Interp/Python.pm line 123.
    Use of chdir('') or chdir(undef) as chdir() is deprecated at /usr/share/perl5/NeedRestart/Interp/Python.pm line 123.
    [Python] #2458: source file not found, skipping
    [Python] #2458:  reduced ARGV: /home/some_user/.local/bin/myscript.py start
    [main] #3080 uses obsolete /usr/lib/postfix/sbin/pickup
    [LXC] #3080 is part of LXC container 'bar_container/system.slice/postfix.service' and should be restarted
    [main] #5058 uses obsolete /usr/lib/postfix/sbin/trivial-rewrite
    [LXC] #5058 is part of LXC container 'foo_container/system.slice/postfix.service' and should be restarted
    [main] #5059 uses obsolete /usr/lib/postfix/sbin/smtp
    [LXC] #5059 is part of LXC container 'foo_container/system.slice/postfix.service' and should be restarted
    [main] #5060 uses obsolete /usr/lib/postfix/sbin/smtp
    [LXC] #5060 is part of LXC container 'foo_container/system.slice/postfix.service' and should be restarted
    [main] #5061 uses obsolete /usr/lib/postfix/sbin/smtp
    [LXC] #5061 is part of LXC container 'foo_container/system.slice/postfix.service' and should be restarted
    [main] #5062 uses obsolete /usr/lib/postfix/sbin/smtp
    [LXC] #5062 is part of LXC container 'foo_container/system.slice/postfix.service' and should be restarted
    [main] #5063 uses obsolete /usr/lib/postfix/sbin/smtp
    [LXC] #5063 is part of LXC container 'foo_container/system.slice/postfix.service' and should be restarted
    [main] #5064 uses obsolete /usr/lib/postfix/sbin/bounce
    [LXC] #5064 is part of LXC container 'foo_container/system.slice/postfix.service' and should be restarted
    [main] #5069 uses obsolete /usr/lib/postfix/sbin/smtp
    [LXC] #5069 is part of LXC container 'foo_container/system.slice/postfix.service' and should be restarted
    [main] #5070 uses obsolete /usr/lib/postfix/sbin/scache
    [LXC] #5070 is part of LXC container 'foo_container/system.slice/postfix.service' and should be restarted
    [main] #5071 uses obsolete /usr/lib/postfix/sbin/smtp
    [LXC] #5071 is part of LXC container 'foo_container/system.slice/postfix.service' and should be restarted
    [main] #5072 uses obsolete /usr/lib/postfix/sbin/smtp
    [LXC] #5072 is part of LXC container 'foo_container/system.slice/postfix.service' and should be restarted
    [main] #5073 uses obsolete /usr/lib/postfix/sbin/smtp
    [LXC] #5073 is part of LXC container 'foo_container/system.slice/postfix.service' and should be restarted
    [main] #5074 uses obsolete /usr/lib/postfix/sbin/bounce
    [LXC] #5074 is part of LXC container 'foo_container/system.slice/postfix.service' and should be restarted
    [main] #5075 uses obsolete /usr/lib/postfix/sbin/smtp
    [LXC] #5075 is part of LXC container 'foo_container/system.slice/postfix.service' and should be restarted
    [main] #5076 uses obsolete /usr/lib/postfix/sbin/smtp
    [LXC] #5076 is part of LXC container 'foo_container/system.slice/postfix.service' and should be restarted
    [main] #5077 uses obsolete /usr/lib/postfix/sbin/smtp
    [LXC] #5077 is part of LXC container 'foo_container/system.slice/postfix.service' and should be restarted
    [main] #5078 uses obsolete /usr/lib/postfix/sbin/smtp
    [LXC] #5078 is part of LXC container 'foo_container/system.slice/postfix.service' and should be restarted
    [main] #5079 uses obsolete /usr/lib/postfix/sbin/smtp
    [LXC] #5079 is part of LXC container 'foo_container/system.slice/postfix.service' and should be restarted
    [main] #5080 uses obsolete /usr/lib/postfix/sbin/smtp
    [LXC] #5080 is part of LXC container 'foo_container/system.slice/postfix.service' and should be restarted
    [main] #5081 uses obsolete /usr/lib/postfix/sbin/smtp
    [LXC] #5081 is part of LXC container 'foo_container/system.slice/postfix.service' and should be restarted
    [main] #5082 uses obsolete /usr/lib/postfix/sbin/smtp
    [LXC] #5082 is part of LXC container 'foo_container/system.slice/postfix.service' and should be restarted
    [main] #5083 uses obsolete /usr/lib/postfix/sbin/smtp
    [LXC] #5083 is part of LXC container 'foo_container/system.slice/postfix.service' and should be restarted
    [main] #5084 uses obsolete /usr/lib/postfix/sbin/smtp
    [LXC] #5084 is part of LXC container 'foo_container/system.slice/postfix.service' and should be restarted
    [main] #5085 uses obsolete /usr/lib/postfix/sbin/smtp
    [LXC] #5085 is part of LXC container 'foo_container/system.slice/postfix.service' and should be restarted
    [main] #5086 uses obsolete /usr/lib/postfix/sbin/smtp
    [LXC] #5086 is part of LXC container 'foo_container/system.slice/postfix.service' and should be restarted
    [main] #5091 uses obsolete /usr/lib/postfix/sbin/bounce
    [LXC] #5091 is part of LXC container 'foo_container/system.slice/postfix.service' and should be restarted
    [Kernel] Linux: kernel release …
    [Kernel/Linux] …
    [Kernel/Linux] Expected linux version: 4.4.0-1-amd64
    Running kernel seems to be up-to-date.
    No services need to be restarted.
    Containers to be restarted:
    Containers being skipped:
     lxc-stop --reboot --name baz_container/system.slice/postfix.service
     lxc-stop --reboot --name foo_container/system.slice/postfix.service
     lxc-stop --reboot --name bar_container/system.slice/postfix.service

**Comment by liske** [comment]
Hi Lukas,

the mapping path detection was broken if a pid had a foreign fs namespace. Fixed.


HTH,
Thomas

**Comment by lpirl** [comment]
Nice, thanks a lot!
