### ISSUE TITLE
RHEL9 RPM Package

### ISSUE THREAD

**Issue by guruguruguru** [liske/needrestart#251]
Hi @duck-rh

It's me again ;-)
do you plan to release needrestart rpm in EPEL9 repository as well?

Thanks a lot!

Dennis

**Comment by duck-rh** [comment]
I do, just need to find some time ;-P.

**Comment by guruguruguru** [comment]
Hey @duck-rh ,
any news here?

**Comment by duck-rh** [comment]
@guruguruguru sorry I forgot to notify here. It reached EPEL9 stable not long ago. You can check the status on the [packaging repo page](https://src.fedoraproject.org/rpms/needrestart).

**Comment by guruguruguru** [comment]
Great news, thank you very much!

**Comment by guruguruguru** [comment]
Do you by chance know how to resolve the dependency on perl(Module::ScanDeps)? 
I cannot find a package providing it in EPEL or elsewhere (but maybe missing a Repo)

**Comment by guruguruguru** [comment]
I will answer this myself:
We are using Oracle Linux 9 and to get needrestart working you need to enable EPEL and codeready builder Repos.

I will close here, thanks again @duck-rh

**Comment by duck-rh** [comment]
On CentOS you need to enable the CRB repo in `/etc/yum.repos.d/centos.repo`.
