### ISSUE TITLE
Support restarting LXD-based containers

### ISSUE THREAD

**Issue by JohnstonJ** [liske/needrestart#26]
As per:

https://github.com/liske/needrestart/blob/f9cd0d3169be4eda7cf84357072ff935c81e9b5d/README.Cont.md

it is stated that there is container support for restarting containers.  Notably absent is LXD: https://linuxcontainers.org/lxd/

If an LXD container is in use, the command for restarting it would be:

```
lxc restart <container>
```

**Comment by liske** [comment]
LXD does not implement containrs but uses LXC in the background. So there is no need to support LXD explicitly, isn't it? Do you have a LXD environment available and did you give the most recent  needrestart a try?

**Comment by JohnstonJ** [comment]
Sort of.  LXD uses liblxc but none of the old LXC command-line tools.  So for example, `lxc-stop` is not even on my system.  So according to the needrestart readme, it can't work since that tool isn't installed.

Even if it was installed, I am not sure if this is advisable or supportable or if it even works.  I think the LXD daemon assumes it has full control over the state of the containers under its control.  See for example the container state management here https://github.com/lxc/lxd/blob/8d58e07c63808b0f13bdf8777fcfe7edcdb352f0/lxd/container_state.go which uses LXD-specific configuration variables, LXD-specific logging, and so forth.  `lxc-stop` would bypass all that and so that sounds fragile to me.

That said, I couldn't find any documentation/guidance on whether this is actually not supported or not.  (They do recommend not mixing LXC and LXD in other ways, e.g. https://github.com/lxc/lxd/commit/33bc6b9a58068fc31bad3b703354d534227aa7b9 ).

**Comment by liske** [comment]
Did you try to run `needrestart` while running a container (under control of *LXD*) using a outdated library? Did *needrestart* already detect the container? If so, it might become hard to differ between pure *LXC* and *LXD* containers...

Could you please provide the content `/proc/<pid>/cgroup` of a process within a LXC container?

**Comment by lenucksi** [comment]
Here are the contents of a process within a LXD container that needrestart wants to restart.

container is the name of the container the process runs in.

> cat /proc/6992/cgroup
> 11:blkio:/lxc/container/system.slice/avahi-daemon.service
> 10:memory:/lxc/container/system.slice/avahi-daemon.service
> 9:pids:/lxc/container/system.slice/avahi-daemon.service
> 8:hugetlb:/lxc/container
> 7:perf_event:/lxc/container
> 6:cpuset:/lxc/container
> 5:net_cls,net_prio:/lxc/container
> 4:freezer:/lxc/container
> 3:cpu,cpuacct:/lxc/container/system.slice/avahi-daemon.service
> 2:devices:/lxc/container/system.slice/avahi-daemon.service
> 1:name=systemd:/lxc/container/system.slice/avahi-daemon.service
