### ISSUE TITLE
Needstart should not restart not running or even disabled services

### ISSUE THREAD

**Issue by j-r-git** [liske/needrestart#269]
Hi,

on my servers, needstart attempts to restart a service even if it is not running. This is the case even if the service is disabled via "systemctl disable some-service". This breaks auto-updates for me.

Is this the intended behaviour, or can this be controlled somehow? The desired behaviour would be that in interactive mode these services are not preselected and in auto mode not restarted.

**Comment by liske** [comment]
I wonder why needrestart should decide to restart a service if it is not running at all. Could you provide a `needrestart -vrl` output for this issue?

**Comment by j-r-git** [comment]
Hi liske,

Thanks very much for your help.

It took me a while to debug this, and it turns out that during an upgrade this service started although it was disabled. So the problem is not related to needrestart - sorry for the false alarm.
