### ISSUE TITLE
Can't use string as an ARRAY ref while "strict refs" in use

### ISSUE THREAD

**Issue by benklop** [liske/needrestart#27]
If I run `needrestart` in my environment, I will sometimes receive `Can't use string ("49989144") as an ARRAY ref while "strict refs" in use at /usr/sbin/needrestart line 348, <> line 2.`

I'm using needrestart 2.7, but line with the issue appears to be the same in 2.8 and master. 
The installed version of perl is 2.14.2, and I've verified all the dependencies are installed.

**Comment by liske** [comment]
There is a ref to `$nrconf{blacklist}` in line 348. I think there is an issue in your needrestart.conf breaking the `blacklist` option.
