### ISSUE TITLE
RaspiOS 12 bookworm breaks kernel name filtering

### ISSUE THREAD

**Issue by rfertig** [liske/needrestart#292]
With RaspiOS 12 Bookworm there are no longer kernels with the name e.g. “kernel7.img”, but “vmlinuz-6.1.0-rpi6-rpi-v7”.

Therefore, there should be an additional note in [needrestart/README.raspberry.md](https://github.com/liske/needrestart/tree/master/README.raspberry.md) that in the case of Bookworm the filter line should look like this:

`$nrconf{kernelfilter} = qr(vmlinuz-.*-v6$);`

**Comment by liske** [comment]
Could one of you create a PR with the required changes handling all RPi cases (I'm not using raspian by myself)?

**Comment by liske** [comment]
IMHO this issue is fixed by #298
