### ISSUE TITLE
Xanmod kernel and needrestart

### ISSUE THREAD

**Issue by og900aero** [liske/needrestart#303]
Hello. I use Xanmod kernel with Debian 12 stable. When I upgrade Xanmod kernel, then needrestart package show message:

![Képernyőkép 2024-05-17 065502](https://github.com/liske/needrestart/assets/49487376/d66a1e79-d51e-415f-9e70-f1fc61dff03a)

I rebooted server and fastfetch show uses new kernel, but needrestart show again this message. What should I do?

**Comment by liske** [comment]
This might be related to #263. Could you apply d3e33025 locally (or switch to git HEAD) to check if the issue is already resolved?

**Comment by og900aero** [comment]
> This might be related to #263. Could you apply [d3e3302](https://github.com/liske/needrestart/commit/d3e33025543cc8459e470379a38c967c362cd4df) locally (or switch to git HEAD) to check if the issue is already resolved?

I installed needrestart from Debian 12 repo (apt install needrestart). Can I get apply patch to this, or I must use git version?

**Comment by liske** [comment]
Try the following patch:

```patch
diff --git a/lib/vmlinuz-get-version b/lib/vmlinuz-get-version
index 3740f25..619a3a3 100755
--- a/lib/vmlinuz-get-version
+++ b/lib/vmlinuz-get-version
@@ -19,8 +19,10 @@
 
 get_version()
 {
-    # search and output version string pattern
-    grep -aom 1 'Linux version [0123456789].*' "$1" && exit 0
+    # search and output version string pattern,
+    # prefer the final version string (linux 6.1+)
+    grep -aoEm 1 'Linux version [[:digit:]].*#[^[:space:]]' "$1" && exit 0
+    grep -aoEm 1 'Linux version [[:digit:]].*#' "$1" && exit 0
 }
 
 try_decompress()
```

To apply this patch run this command `patch /usr/lib/needrestart/vmlinuz-get-version` as root and paste the patch to stdin. This change will be overriden next time you upgrade or reinstall needrestart.

**Comment by og900aero** [comment]
> patch /usr/lib/needrestart/vmlinuz-get-version

I applied this patch, but when I run sudo needrestart, I get message (like first post) again.

**Comment by liske** [comment]
A reboot ist not required, can you please provide the output of `needrestart -v -k` ?

**Comment by og900aero** [comment]
> A reboot ist not required, can you please provide the output of `needrestart -v -k` ?

╰─$ sudo needrestart -v -k
[main] eval /etc/needrestart/needrestart.conf
[main] needrestart v3.6
[main] running in root mode
[Core] Using UI 'NeedRestart::UI::stdio'...
[main] systemd detected
[Kernel] Linux: kernel release 6.10.3-x64v3-xanmod1, kernel version #0~20240804.ga89cde1 SMP PREEMPT_DYNAMIC Sun Aug  4 06:16:42 UTC
Failed to load NeedRestart::Kernel::kFreeBSD: [Kernel/kFreeBSD] Not running on GNU/kFreeBSD!
[Kernel/Linux] /boot/vmlinuz-6.10.3-x64v3-xanmod1 => 6.10.3-x64v3-xanmod1 (root@runner-6areqvs9r-project-51590166-concurrent-0) #0~20240804.ga89cde1 SMP PREEMPT_DYNAMIC Sun Aug  4 0 [6.10.3-x64v3-xanmod1]
[Kernel/Linux] /boot/vmlinuz-6.9.11-x64v3-xanmod1 => 6.9.11-x64v3-xanmod1 (root@runner-huzfz3a5r-project-51590166-concurrent-0) #0~20240725.gd9c0ea3 SMP PREEMPT_DYNAMIC Thu Jul 25 1 [6.9.11-x64v3-xanmod1]
[Kernel/Linux] Expected linux version: 6.10.3-x64v3-xanmod1

Pending kernel upgrade!

Running kernel version:
  6.10.3-x64v3-xanmod1

Diagnostics:
  The currently running kernel has an ABI compatible upgrade pending.

Restarting the system to load the new kernel will not be handled automatically, so you should consider rebooting. [Return]

**Comment by phd** [comment]
> Try the following patch:

I patched `vmlinuz-get-version`, but the issue still occurs:

```
$ needrestart -v -k
[main] eval /etc/needrestart/needrestart.conf
[main] needrestart v3.6
[main] running in user mode
[Core] Using UI 'NeedRestart::UI::stdio'...
[main] systemd detected
[Kernel] Linux: kernel release 6.10.3-x64v3-xanmod1, kernel version #0~20240804.ga89cde1 SMP PREEMPT_DYNAMIC Sun Aug  4 06:16:42 UTC
Failed to load NeedRestart::Kernel::kFreeBSD: [Kernel/kFreeBSD] Not running on GNU/kFreeBSD!
[Kernel/Linux] /boot/vmlinuz.old => 6.10.3-x64v3-xanmod1 (root@runner-6areqvs9r-project-51590166-concurrent-0) #0~20240804.ga89cde1 SMP PREEMPT_DYNAMIC Sun Aug  4 0 [6.10.3-x64v3-xanmod1]
[Kernel/Linux] /boot/vmlinuz-6.10.3-x64v3-xanmod1 => 6.10.3-x64v3-xanmod1 (root@runner-6areqvs9r-project-51590166-concurrent-0) #0~20240804.ga89cde1 SMP PREEMPT_DYNAMIC Sun Aug  4 0 [6.10.3-x64v3-xanmod1]
[Kernel/Linux] /boot/vmlinuz-6.9.12-x64v3-xanmod1 => 6.9.12-x64v3-xanmod1 (root@runner-5zaukmnig-project-51590166-concurrent-0) #0~20240728.ge137ddd SMP PREEMPT_DYNAMIC Sun Jul 28 1 [6.9.12-x64v3-xanmod1]
[Kernel/Linux] Could not open linux image (/boot/vmlinuz-6.8.0-40-generic): Permission denied
+ mktemp
+ tmp=/tmp/tmp.UqHFa0TJ1t
+ trap rm -f /tmp/tmp.UqHFa0TJ1t 0
+ get_version /boot/vmlinuz-6.8.0-40-generic
+ grep -aoEm 1 Linux version [[:digit:]].*#[^[:space:]] /boot/vmlinuz-6.8.0-40-generic
grep: /boot/vmlinuz-6.8.0-40-generic: Permission denied
+ grep -aoEm 1 Linux version [[:digit:]].*# /boot/vmlinuz-6.8.0-40-generic
grep: /boot/vmlinuz-6.8.0-40-generic: Permission denied
+ which gunzip
+ try_decompress \037\213\010 xy gunzip
/usr/lib/needrestart/vmlinuz-get-version: 36: cannot open /boot/vmlinuz-6.8.0-40-generic: Permission denied
+ grep -abo ^xy
+ which unxz
+ try_decompress \3757zXZ\000 abcde unxz
/usr/lib/needrestart/vmlinuz-get-version: 36: cannot open /boot/vmlinuz-6.8.0-40-generic: Permission denied
+ grep -abo ^abcde
+ which bunzip2
+ try_decompress BZh xy bunzip2
/usr/lib/needrestart/vmlinuz-get-version: 36: cannot open /boot/vmlinuz-6.8.0-40-generic: Permission denied
+ grep -abo ^xy
+ which unlzma
+ try_decompress \135\0\0\0 xxx unlzma
/usr/lib/needrestart/vmlinuz-get-version: 36: cannot open /boot/vmlinuz-6.8.0-40-generic: Permission denied
+ grep -abo ^xxx
+ which lzop
+ try_decompress \211\114\132 xy lzop -d
/usr/lib/needrestart/vmlinuz-get-version: 36: cannot open /boot/vmlinuz-6.8.0-40-generic: Permission denied
+ grep -abo ^xy
+ rm -f /tmp/tmp.UqHFa0TJ1t
[Kernel/Linux] version from filename: 6.8.0-40-generic
[Kernel/Linux] /boot/vmlinuz-6.8.0-40-generic => 6.8.0-40-generic [6.8.0-40-generic]
[Kernel/Linux] Could not open linux image (/boot/vmlinuz): Permission denied
+ mktemp
+ tmp=/tmp/tmp.nXB5hAHXfQ
+ trap rm -f /tmp/tmp.nXB5hAHXfQ 0
+ get_version /boot/vmlinuz
+ grep -aoEm 1 Linux version [[:digit:]].*#[^[:space:]] /boot/vmlinuz
grep: /boot/vmlinuz: Permission denied
+ grep -aoEm 1 Linux version [[:digit:]].*# /boot/vmlinuz
grep: /boot/vmlinuz: Permission denied
+ which gunzip
+ try_decompress \037\213\010 xy gunzip
/usr/lib/needrestart/vmlinuz-get-version: 36: cannot open /boot/vmlinuz: Permission denied
+ grep -abo ^xy
+ which unxz
+ try_decompress \3757zXZ\000 abcde unxz
+ /usr/lib/needrestart/vmlinuz-get-version: 36: cannot open /boot/vmlinuz: Permission denied
grep -abo ^abcde
+ which bunzip2
+ try_decompress BZh xy bunzip2
/usr/lib/needrestart/vmlinuz-get-version: 36: cannot open /boot/vmlinuz: Permission denied
+ grep -abo ^xy
+ which unlzma
+ try_decompress \135\0\0\0 xxx unlzma
/usr/lib/needrestart/vmlinuz-get-version: 36: cannot open /boot/vmlinuz: Permission denied
+ grep -abo ^xxx
+ which lzop
+ try_decompress \211\114\132 xy lzop -d
/usr/lib/needrestart/vmlinuz-get-version: 36: cannot open /boot/vmlinuz: Permission denied
+ grep -abo ^xy
+ rm -f /tmp/tmp.nXB5hAHXfQ
[Kernel/Linux] Could not get version string from /boot/vmlinuz.
[Kernel/Linux] Expected linux version: 6.10.3-x64v3-xanmod1

Pending kernel upgrade!

Running kernel version:
  6.10.3-x64v3-xanmod1

Diagnostics:
  The currently running kernel has an ABI compatible upgrade pending.

Restarting the system to load the new kernel will not be handled automatically, so you should consider rebooting.
[Return]
```
```
KERNELS:
     - vmlinuz-6.8.0-40-generic
     - vmlinuz-6.9.12-x64v3-xanmod1
     - vmlinuz-6.10.3-x64v3-xanmod1
CURRENT: Linux 6.10.3-x64v3-xanmod1
```

**Comment by liske** [comment]
Thanks for checking.

Sadly the above patch was incomplete. I've tested needrestart's git HEAD on a test vm with xanmod kernel and the issue did disappear.

**Comment by phd** [comment]
> needrestart's git HEAD on a test vm with xanmod kernel and the issue did disappear.

How can I run needrestart from git?
`# ./needrestart` doesn't seem to work.
Do I have to `make install`?

**Comment by og900aero** [comment]
> > needrestart's git HEAD on a test vm with xanmod kernel and the issue did disappear.
> 
> How can I run needrestart from git? `# ./needrestart` doesn't seem to work. Do I have to `make install`?

sudo apt remove needrestart
git clone https://github.com/liske/needrestart.git
cd needrestart/ 
sudo make install
