### ISSUE TITLE
On old Raspberry Pi, the wrong kernel is expected

### ISSUE THREAD

**Issue by beta-tester** [liske/needrestart#316]
if i run needrestart on an RPi Zero W (the old one) or on an RPi 1 B , i get the folowing output:
```
$ needrestart -rl

Pending kernel upgrade!

Running kernel version:
  6.6.51+rpt-rpi-v6

Diagnostics:
  The currently running kernel version is not the expected kernel version 6.6.51+rpt-rpi-v8.

Restarting the system to load the new kernel will not be handled automatically, so you should consider rebooting. [Return]

The processor microcode seems to be up-to-date.
No services need to be restarted.
No containers need to be restarted.
No user sessions are running outdated binaries.
No VM guests are running outdated hypervisor (qemu) binaries on this host.
```

the old RPi Zero or RPi 1B will never be able to run the modern 64bit kernel *-rpi-V8

i guess the RPi 2 will get/show the same wrong expected kernel image.

[Raspberry Pi hardware](https://www.raspberrypi.com/documentation/computers/raspberry-pi.html)
[Build configuration](https://www.raspberrypi.com/documentation/computers/linux_kernel.html#native-build-configuration)

**Comment by liske** [comment]
needrestart expects by default that the most recent kernel image should be used. The kernel images can be filtered by changing needrestart's default configuration. For RPi it is documented in `README.raspberry.md`.

I'm going to close this issue as this is an issue which cannot be fixed in needrestart  IMHO. It might be fixable in the needrestart package of the OS.

**Comment by beta-tester** [comment]
> needrestart expects by default that the most recent kernel image should be used. The kernel images can be filtered by changing needrestart's default configuration. For RPi it is documented in `README.raspberry.md`.
> 
> I'm going to close this issue as this is an issue which cannot be fixed in needrestart IMHO. It might be fixable in the needrestart package of the OS.

thank you, and sorry that i havn't carefully read the documentation. *shame in me*
