### ISSUE TITLE
Documentation: incorrect syntax or encoding in markdown file

### ISSUE THREAD

**Issue by mikkorantalainen** [liske/needrestart#318]
The `<pid>` in
```text/plain
There are special packages (NeedRestart::Interp::*) implementing the
source code file list extraction. The executable (/proc/<pid>/exec) is
used to detect the running interpreter.
```
needs to be escaped because it gets interpreted as XML markup in https://github.com/liske/needrestart/blob/539233750b59ed3b39cb763f5ad43243c2eaf562/README.Interp.md

I'd recommend writing it as ``The executable (`/proc/<pid>/exec`) is ...``

https://github.com/liske/needrestart/blob/539233750b59ed3b39cb763f5ad43243c2eaf562/README.Interp.md?plain=1#L7

I didn't check if there are other locations in the same or other documentation files with the same error type.

**Comment by liske** [comment]
This was the only one in markdown files missing backtick. Thanks!
