### ISSUE TITLE
Consider providing RPM packages

### ISSUE THREAD

**Issue by lenucksi** [liske/needrestart#36]
Hello,
as a CentOS / Amazon Linux user I would like to be able to use native rpm packages for needrestart.
I've seen that https://github.com/pantheon-systems/needrestart-rpm appears to provide a spec plus some tooling for needrestart.
Also, I've made up a needrestart package using fpm and could maybe provide the spec for it, or the script that I used to create the package.

It would be nice to have needrestart in either EPEL or some other publicly RPM repo. 
There are companies such as https://bintray.io/ or https://packagecloud.io/ that provide free package repos, maybe one could provide packages there, if the integration into a larger distro is not possible.

Other than that: needrestart is a very nice tool! 👍

**Comment by liske** [comment]
Hi,

sorry, but I'm not going to release any pre-build packages. Please consider requesting the community of your preferred GNU/Linux distribution to package it. I'm OK with merging a working spec file upstream.

HTH,
Thomas

**Comment by lenucksi** [comment]
Ok, let's see if the spec file I have is good enough. I'll bring up a PR once I have more.
