### ISSUE TITLE
Error messages and high cpu usage while scanning

### ISSUE THREAD

**Issue by bxkx** [liske/needrestart#41]
Hello, can anybody help me? Every time I apt-get upgrade and needrestart starts scanning it also shows me the following:

```
# Use of runtime loader module Module::Implementation detected.  Results of static scanning may be incomplete.
# Use of runtime loader module Module::Runtime detected.  Results of static scanning may be incomplete.
```

The CPU usage is kind of spiking when that happens. I'm on Debian 8.

**Comment by r-lindner** [comment]
I get the same messages when it tries to detect updates in the Thruk package in Debian 8. This breaks the nagios plugin mode.

**Comment by liske** [comment]
Could you please provide the output of `needrestart -v` when the problem does occur? We need to figure out the conditions triggering those messages and the increased CPU load.

**Comment by r-lindner** [comment]
Here are the logs for -v and -p: [out.txt](https://github.com/liske/needrestart/files/563550/out.txt)

**Comment by r-lindner** [comment]
oh by the way: I am using 2.9-1~bpo8+1 (jessie-backports).
In 2.8.1 the CPU-usage was much higher and it needed about 10 seconds after displaying the "# Use of runtime..." messages.
This has vanished in 2.9.1 - only the messages remain, which are bad in the Nagios-plugin output.

**Comment by liske** [comment]
Thanks for the logs!

* **Warnings:** This is triggered by Module::ScanDeps for dynamic loaded modules. The warning messages seems to be hard coded - I need to check how to supress them...

* **CPU usage:** There was a caching layer added in 2.9 (Debian Bug#826247) to stop parsing interpreter source files twice which improves the scan time if you have many interpreter instances running.
