### ISSUE TITLE
Needrestart hangs with LXD containers

### ISSUE THREAD

**Issue by lenucksi** [liske/needrestart#43]
I use needrestart with a standard Ubuntu 16.04 together with LXD (basically LXC+scripting, see https://linuxcontainers.org/lxd/ ) containers using the package provided by Ubuntu.
Needrestart runs fine, however hangs after the check started by aptitude.

> SET needrestart/ui-query_conts LXC container/system.slice/avahi-daemon.service, LXC container/system.slice/dbus.service

It usually suffices to CTRL-C the process, however this is a problem with unattended updates...
#26 appears to be relevant to this case too.

**Comment by lenucksi** [comment]
This ends up locking apt-databases due to hanging nightly update jobs that can not properly terminate the package manager due this bug.

**Comment by liske** [comment]
Hi,

you should never see the debconf stuff (`SET ...`) on you TTY. It seems something breaks the pipe setup between *debconf* and *needrestart*.

**Comment by liske** [comment]
You are using needrestart 2.6, didn't you? There is a bug before needrestart 2.8 which was fixed by 0131e9f4638a774a460f02e5e940c6bf6106a6ba breaking debconf for the container selection.

**Comment by lenucksi** [comment]
I was actually using needrestart version 2.9.

**Comment by liske** [comment]
Could you give git HEAD a try? You will find a most recently build Debian package attached to https://github.com/liske/needrestart/issues/54#issuecomment-272725461

**Comment by lenucksi** [comment]
Thanks, I'll report a new status once I've got a situation that should trigger the bug.

**Comment by liske** [comment]
Please use the offical packages 2.11-2 from _[jessie-backports](https://packages.debian.org/search?suite=jessie-backports&keywords=needrestart)_ or _[stretch](https://packages.debian.org/search?suite=stretch&keywords=needrestart)_ for further troubleshooting. Thanks!

**Comment by lenucksi** [comment]
Could you try to bring that into Ubuntu or provide a Ubuntu PPA for it too?

**Comment by liske** [comment]
I'm not using Ubuntu at all so I'm not going to provide any PPA for it. I'll close this issue, feel free to reopen it if you where able to reproduce the bug with needrestart 2.11+ so we can do further debugging.
