### ISSUE TITLE
Configurable exclusion of temporary files

### ISSUE THREAD

**Issue by stbuehler** [liske/needrestart#45]
Various programs create temporary files and map / open them:
- Gerrit
  - `.../reviewsite/tmp/gerrit_7939865497111433863_app/gerrit-common-server.jar` and similar
- Jenkins
  - `/tmp/jna--1712433994/jna8262265615257149299.tmp` (executable mapping)
  - `/tmp/winstone7812778614686151261.jar` ("obsolete script file")

It would be nice if one could specify a list of regular expressions to ignore such files; right now I manually ignore `m@/tmp/@` in `/usr/sbin/needrestart` line 438 and in `Interp/Java.pm`.

**Comment by liske** [comment]
It is already possible to configure the blacklist used for the interpreter detection stuff (see also #39). Do you think it is realy required to add such an option for mappings?

**Comment by stbuehler** [comment]
I guess #39 covers the interpreter files.

You already hardcoded so many special cases, like this:

```perl
# skip Oil Runtime Compiler's JIT files
next if($path =~ m@/orcexec\.[\w\d]+( \(deleted\))?$@);
```

You really think one day you'll get them all? You have some `/tmp` handling, but it obviously failed JNA. I think it is really time you added a way to configure this blacklist, whether by list of regex or even a hook function.

**Comment by martux69** [comment]
Hi,
I would like to ask for help for configuring the right regex at the right place in needrestart.conf .
I would like to exclude such kind of files:

> [main] #11007 uses deleted /export/home/trvppi01/tmp/jna-1883853682/jna153473689760224350.tmp
[main] #11007 is a child of #10996
[main] #11138 uses deleted /export/home/trvppi01/tmp/jna-1883853682/jna7073174604953435872.tmp
[main] #11138 is a child of #11127

Where must I set the regex ? In $nrconf{blacklist_mappings} or in $nrconf{blacklist_interp} ? Is this the right regex for it: qr#/export\.[\w\d]+( \(tmp\))?$#

Thanks for helping.

Kind regards

Martin
