### ISSUE TITLE
Java services - temp files detected as false positives

### ISSUE THREAD

**Issue by taladar** [liske/needrestart#48]
On a system running Jenkins

```
[main] #244 uses deleted /tmp/jna--1712433994/jna7942230164883463296.tmp
[main] #244 is a child of #242
[...]
[main] #242 exe => /usr/bin/daemon
[main] #242 is jenkins.service
Services to be restarted:
 systemctl restart jenkins.service
```

On a system running puppetserver (uses jruby)

```
[main] #1418 uses deleted /tmp/jffi2434865470457235499.so
[main] #1418 is not a child
[...]
[main] #1418 exe => /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
[Core] #1418 is a NeedRestart::Interp::Java
[Core] #1418 source is UNKNOWN
[main] #1418 is puppetserver.service
[...]
Services to be restarted:
 systemctl restart puppetserver.service

```

When restarting either service the same situation is immediately created again.

**Comment by liske** [comment]
In `needrestart` v2.10 this issue should not exist any more (see also #45).

**Comment by taladar** [comment]
I managed to exclude the files using that new mechanism. Thanks for your help. Our config file template came from an older version and did not have the current default settings yet for those new features.
