### ISSUE TITLE
Use of runtime loader module Module::Implementation detected

### ISSUE THREAD

**Issue by TomaszUrugOlszewski** [liske/needrestart#51]
This warning exists on munin servers (Debian Jessie) with needrestart 2.9 installed from backports

```
$ needrestart  -p
# Use of runtime loader module Module::Implementation detected.  Results of static scanning may be incomplete.
# Use of runtime loader module Module::Runtime detected.  Results of static scanning may be incomplete.

```

Both packages are installed
- libmodule-implementation-perl
- libmodule-runtime-perl

Not sure if it's needrestart problem.

**Comment by liske** [comment]
Yes, it *was*. The issue had been fixed in #41 which is included in needrestart 2.10 (which is in stretch, but not in bpo, yet).
