### ISSUE TITLE
Always detecting nagios3.service as service to restart

### ISSUE THREAD

**Issue by wforumw** [liske/needrestart#53]
Hi,
I use needrestart on jessie from jessie-backports. I have the problem that nagios3.service is always detected
I also tried it wit the version from stretch but the issue still exist

**Comment by liske** [comment]
Could you please provide the verbose output of the newest needrestart available?

**Comment by wforumw** [comment]
#needrestart -v
[main] eval /etc/needrestart/needrestart.conf
[main] running in root-mode
[Core] Using UI 'NeedRestart::UI::stdio'...
[main] detected systemd
[main] #896 uses deleted /var/lib/nagios3/spool/checkresults/nebmodkl9VxP
[main] #896 is not a child
[Core] #1066 is a NeedRestart::Interp::Python
[Python] #1066: source=/usr/bin/fail2ban-server
[main] #9544 uses deleted /var/lib/nagios3/spool/checkresults/nebmodkl9VxP
[main] #9544 is a child of #896
[main] #11771 uses deleted /var/lib/nagios3/spool/checkresults/nebmodkl9VxP
[main] #11771 is a child of #896
[main] #12090 uses deleted /var/lib/nagios3/spool/checkresults/nebmodkl9VxP
[main] #12090 is a child of #896
[main] #12868 uses deleted /var/lib/nagios3/spool/checkresults/nebmodkl9VxP
[main] #12868 is a child of #896
[main] #896 exe => /usr/sbin/nagios3
[main] #896 is nagios3.service
[Kernel] Linux: kernel release 3.16.0-4-686-pae, kernel version #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19)
Failed to load NeedRestart::Kernel::kFreeBSD: [Kernel/kFreeBSD] Not running on GNU/kFreeBSD!
[Kernel/Linux] /boot/vmlinuz-3.16.0-4-686-pae => 3.16.0-4-686-pae (debian-kernel@lists.debian.org) #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) [3.16.0-4-686-pae]*
[Kernel/Linux] Expected linux version: 3.16.0-4-686-pae
Running kernel seems to be up-to-date.
Restarting services...
Services to be restarted:
Restart «nagios3.service»? [Ynas?] y
 systemctl restart nagios3.service
No containers need to be restarted.
No user sessions are running outdated binaries.

**Comment by liske** [comment]
It seems that you are using some special NEB module which uses some  executable stuff inside /var/lib/nagios3/spool/checkresults. It should be sufficient to add the path to `$nrconf{blacklist_mappings}`.

**Comment by wforumw** [comment]
Thanks!!
Now it works

**Comment by liske** [comment]
The stuff within */var/lib/nagios3/spool//checkresults* is some dynamic binary blob - nothing to worry about. needrestart will stil suggest to restart nagios if it uses some obsolete libs within */usr/lib*.
