### ISSUE TITLE
Use of uninitialized value

### ISSUE THREAD

**Issue by pigen** [liske/needrestart#58]
Hello,

After upgrading to needrestart 2.11 ( #57 ) from jessie backport the postfix service is always "need restart" (it's fixed 2.10, or not? #46 ), and I get these warnings all the time:

> Use of uninitialized value $testp in stat at /usr/sbin/needrestart line 462, <HMAP> line 1.
> Use of uninitialized value $sdev in right bitshift (>>) at /usr/sbin/needrestart line 463, <HMAP> line 1.
> Use of uninitialized value $sdev in right bitshift (>>) at /usr/sbin/needrestart line 463, <HMAP> line 1.
> Use of uninitialized value $sdev in bitwise and (&) at /usr/sbin/needrestart line 463, <HMAP> line 1.
> Use of uninitialized value $sdev in right bitshift (>>) at /usr/sbin/needrestart line 463, <HMAP> line 1.
> Use of uninitialized value $sdev in right bitshift (>>) at /usr/sbin/needrestart line 463, <HMAP> line 1.
> Use of uninitialized value $sdev in bitwise and (&) at /usr/sbin/needrestart line 463, <HMAP> line 1.
> Use of uninitialized value $sdev in right bitshift (>>) at /usr/sbin/needrestart line 475, <HMAP> line 1.
> Use of uninitialized value $sdev in right bitshift (>>) at /usr/sbin/needrestart line 475, <HMAP> line 1.
> Use of uninitialized value $sinode in string eq at /usr/sbin/needrestart line 480, <HMAP> line 1.

The full needrestart message:

root@franky.local:/home/pigen# needrestart -v
[main] eval /etc/needrestart/needrestart.conf
[main] needrestart v2.11
[main] running in root mode
[Core] Using UI 'NeedRestart::UI::stdio'...
[main] detected systemd
Use of uninitialized value $testp in stat at /usr/sbin/needrestart line 462, <HMAP> line 1.
Use of uninitialized value $sdev in right bitshift (>>) at /usr/sbin/needrestart line 463, <HMAP> line 1.
Use of uninitialized value $sdev in right bitshift (>>) at /usr/sbin/needrestart line 463, <HMAP> line 1.
Use of uninitialized value $sdev in bitwise and (&) at /usr/sbin/needrestart line 463, <HMAP> line 1.
Use of uninitialized value $sdev in right bitshift (>>) at /usr/sbin/needrestart line 463, <HMAP> line 1.
Use of uninitialized value $sdev in right bitshift (>>) at /usr/sbin/needrestart line 463, <HMAP> line 1.
Use of uninitialized value $sdev in bitwise and (&) at /usr/sbin/needrestart line 463, <HMAP> line 1.
Use of uninitialized value $sdev in right bitshift (>>) at /usr/sbin/needrestart line 475, <HMAP> line 1.
Use of uninitialized value $sdev in right bitshift (>>) at /usr/sbin/needrestart line 475, <HMAP> line 1.
Use of uninitialized value $sinode in string eq at /usr/sbin/needrestart line 480, <HMAP> line 1.
[main] #3226 uses obsolete /usr/lib/postfix/pickup
[main] #3226 is a child of #3225
[main] #3225 exe => /usr/lib/postfix/master
[main] #3225 is postfix.service
[Kernel] Linux: kernel release 4.8.0-2-grsec-amd64, kernel version #1 SMP Debian 4.8.15-2+grsec201701031913+1~bpo8+1 (2017-01-28)
[Kernel/Linux] /boot/vmlinuz-4.8.0-2-grsec-amd64 => 4.8.0-2-grsec-amd64 (corsac@debian.org) #1 SMP Debian 4.8.15-2+grsec201701031913+1bpo8+1 (2017-01-28)▒+a+▒+
, [4.8.0-2-grsec-amd64]*
[Kernel/Linux] /boot/vmlinuz-3.16.0-4-amd64 => 3.16.0-4-amd64 (debian-kernel@lists.debian.org) #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) [3.16.0-4-amd64]
[Kernel/Linux] Expected linux version: 4.8.0-2-grsec-amd64
Running kernel seems to be up-to-date.
Restarting services...
Services to be restarted:
Restart «postfix.service»? [Ynas?] no
Services being skipped:
 systemctl restart postfix.service
No containers need to be restarted.
No user sessions are running outdated binaries.

root@franky.local:/home/pigen# uname -a
Linux franky.local 4.8.0-2-grsec-amd64 #1 SMP Debian 4.8.15-2+grsec201701031913+1~bpo8+1 (2017-01-28) x86_64 GNU/Linux

root@franky.local:/home/pigen# lsb_release -a

    No LSB modules are available.
    Distributor ID: Debian
    Description: Debian GNU/Linux 8.7 (jessie)
    Release: 8.7
    Codename: jessie

root@franky.local:/home/pigen# dpkg -l | grep grsec

    ii gradm2 3.0201408301734-1 amd64 Administration program for the grsecurity2 RBAC based ACL system
    ii linux-grsec-base 11bpo8+1 all Linux image base package, grsec featureset
    ii linux-image-4.8.0-2-grsec-amd64 4.8.15-2+grsec201701031913+1bpo8+1 amd64 Linux 4.8 for 64-bit PCs, Grsecurity protection
    ii linux-image-grsec-amd64 11bpo8+1 amd64 Linux image meta-package, grsec featureset

root@franky.local:/home/pigen# dpkg -l | grep needrestart
ii  needrestart                     2.11-bpo8+1                       all          check which daemons need to be restarted after library upgrades

BR,
Tamás

**Comment by liske** [comment]
Thanks, the handling of file existence check was broken for library mappings in `(/var)?/tmp`.
