### ISSUE TITLE
Useless use of '\'

### ISSUE THREAD

**Issue by larsen0815** [liske/needrestart#62]
I have installed the current master (2.11). needrestart shows a warning upon execution:

````
root@vm-ubuntu:~# needrestart -v
[main] eval /etc/needrestart/needrestart.conf
Useless use of '\'; doesn't escape metacharacter '(' at (eval 18) line 153, <> line 1.
[main] needrestart v2.11
````
Running on Ubuntu Trusty.

**Comment by liske** [comment]
This is a regression in Perl 5.20 (i.e. Debian jessie), newer (and older) version of Perl don't report this warning.
