### ISSUE TITLE
Improve documentation regarding installation of needrestart

### ISSUE THREAD

**Issue by larsen0815** [liske/needrestart#63]
I needed to manually install needrestart and couldn't find any documentation on it, only some prerequisites. This should be improved:

````
# Install prerequisites, s. https://github.com/liske/needrestart/blob/master/INSTALL.md
apt-get -y install libmodule-find-perl libmodule-scandeps-perl libproc-processtable-perl libsort-naturally-perl libterm-readkey-perl libintl-perl gettext po-debconf xz-utils

# Set variable to the desired version
export VERSION="2.10"

# Download and install
wget "https://github.com/liske/needrestart/archive/v${VERSION}.zip" && \
unzip v${VERSION}.zip && \
cd needrestart-${VERSION} && \
make install
````

Tested with Ubuntu Precise and Trusty.

**Comment by liske** [comment]
The required packages are listed in INSTALL and using `make install` is the traditional way to install.

**Comment by larsen0815** [comment]
The INSTALL is a stub. I have prepared everything for an installation on Debian and Ubuntu systems, which would make it much easier for users. Don't understand why you refuse to simply copy/paste this into INSTALL... This doesn't encourage me to help the project any further.
