### ISSUE TITLE
kde plasmashell: deleted mmapped file

### ISSUE THREAD

**Issue by GoTeamAnt** [liske/needrestart#65]
Hi

I am using archlinux / kde and recent versions of plasmashell leave a deleted memory mapped file behind:

```
from /proc/$pasmashellid/maps:
7f5d4c106000-7f5d4c146000 rw-s 00000000 08:03 9699936                    /home/user/#9699936 (deleted)
7f5d4c146000-7f5d4c186000 r-xs 00000000 08:03 9699936                    /home/user/#9699936 (deleted)
```

I have added this filter to the blacklist_mappings in my needrestart.conf 

`    qr(/home/[\w]+/#[\d]+( \(deleted\))?$),
`

I am shure the regex can be improved, because the filename is derived from the inode number, but this version is good enough for me.

Please consider adding this filter.

**Comment by liske** [comment]
Thanks, I've improved the regex to match everywhere in case the home directory is mounted somewhere else than `/home`.
