### ISSUE TITLE
Can't preseed

### ISSUE THREAD

**Issue by PeteLawler** [liske/needrestart#66]
I'm not overly well versed in debconf, however...

I'm trying to install needrestart using preseed on jessie. I've set it up in my 'd-i pkgsel/include' section, and it seems to want to install fine. However, it gets stuck because the preseed is upgrading the kernel on install. This generates a warning.

I took a look at an existing install, and unconvered
unknown needrestart/ui-kernel_announce_abi note

This got me trying a few things, notably putting this into the preseed as well as replacing 'unknown' with 'needrestart'.

Neither approach appear to work.

I've noticed that the needrestart.template gets installed into /usr/share/needrestart/needrestart.templates and in face that's the only d-i template I have on my system in /usr/share, all others appear in /var/lib/dpkg/info which, curiously enough, I also find needrestart.conffiles  needrestart.list  needrestart.md5sums  needrestart.postinst  needrestart.postrm and needrestart.preinst.

Now I'm not entirely sure if this is a problem with the code as written here, or with whoever puts the debian image together. Any advice guidance etc. appreciated.

**Comment by liske** [comment]
needrestart uses debconf in a different way than regular package's configure scripts. It is not possible to preseed it since needrestart resets the queries on every run.

To prevent needrestart to "stuck" your installation you could use a non-interactive debconf frontend or maybe configure needrestart to list only mode.

**Comment by PeteLawler** [comment]
Fair enough, but i am still unsure how I can configure preseed for list only mode in the preseed. There doesn't immediately appear to be anything in the preseed template I can use to force an install time configure of list only (as I say, though, I'm not everly familiar with how debconf stuff works so am not unlikely to bemissing something)

**Comment by liske** [comment]
Needrestart is *not* configured by debconf. Debconf is only one way to query the user for restarts. You can override needrestart's configuration file content by files within `/etc/needrestart/conf.d/` (i.e. ` $nrconf{restart} = 'l'`).

**Comment by liske** [comment]
The fix for issue #71 might help you to prevent *needrestart* to be run by the apt-get hook.
