### ISSUE TITLE
Kernel version sort incorrect for RHEL

### ISSUE THREAD

**Issue by mxey** [liske/needrestart#73]
needrestart sorts RHEL kernel versions incorrectly:

```
[root@host~]# needrestart -k -b
NEEDRESTART-VER: 2.9
NEEDRESTART-KCUR: 3.10.0-693.1.1.el7.x86_64
NEEDRESTART-KEXP: 3.10.0-693.el7.x86_64
NEEDRESTART-KSTA: 3
```

That output is from needrestart 2.9, but I have a small test that reproduces the problem on latest Git master:

```perl
#!/usr/bin/perl
use v5.14;
use warnings;
use Test::More tests => 1;

use lib 'perl/lib';

use NeedRestart::Kernel;

my @kernels = qw(
    3.10.0-693.1.1.el7.x86_64
    3.10.0-693.el7.x86_64
    3.10.0-514.21.1.el7.x86_64
    3.10.0-327.el7.x86_64
);
my ($version) = reverse sort {nr_kernel_vcmp($a, $b);} @kernels;

is $version, '3.10.0-693.1.1.el7.x86_64';
```

Output:
```
1..1
not ok 1
#   Failed test at /…/kernel_sort.t line 18.
#          got: '3.10.0-693.el7.x86_64'
#     expected: '3.10.0-693.1.1.el7.x86_64'
# Looks like you failed 1 test of 1.
```

**Comment by liske** [comment]
Is there any documentation available  on howto compare RHEL (kernel) versions?

**Comment by mxey** [comment]
I don't think so, except the implementation of "rpmvercmp” in RPM. I found this Perl module that implements it though: https://metacpan.org/pod/RPM::VersionSort

**Comment by liske** [comment]
I've adopted the version handling of RPM::VersionSort which will be used on RHEL environments (there is a line `using RPM version sorting` in verbose mode). It seems to work with your test.

Thanks for reporting this issue.

**Comment by mxey** [comment]
I took a quick look at your commit. You only check for /etc/redhat-version, which I see neither on RHEL nor CentOS. I have a /etc/redhat-release though.

The combined check for the absence of dpkg might lead to a false negative, in case somebody has installed dpkg (which you can do, just like the RPM tools are available in Debian)

**Comment by liske** [comment]
Thanks for looking at the commit.

- **`/etc/redhat-release`** - this was a typo, I should have used copy'n'paste ;-)
- **dpkg** - I did not expect that dpkg can be installed as rpm on Debian. I've replaced the check by testing if `/etc/debian_version` does **not** exist.
