### ISSUE TITLE
no libnotify notifications if dbus user session is used

### ISSUE THREAD

**Issue by Vladimir-csp** [liske/needrestart#76]
If dbus-user-session is used instead of dbus-x11, libnotify notifications do not work.

To solve this:
`export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u $NR_USERNAME)/bus"`
But I do not know it it will break notifications with dbus-x11. Perhaps, some condition is needed.

Offtopic: btw you can add `-a needrestart` to notify-send command to set application name in notifications

**Comment by lluis** [comment]
on my Debian 10.1 notifications was not working and this was delaying apt runs for 50 seconds:
```00:05:49 stretch sudo[4987]: lluis : TTY=pts/1 ; PWD=/home/lluis ; USER=root ; COMMAND=/usr/sbin/needrestart
00:05:49 stretch sudo[4987]: pam_unix(sudo:session): session opened for user root by lluis(uid=0)
00:05:49 stretch su[5022]: (to lluis) lluis on none
00:05:49 stretch su[5022]: pam_unix(su:session): session opened for user lluis by (uid=0)
00:05:50 stretch dbus-daemon[3636]: [session uid=1000 pid=3634] Activating service name='org.freedesktop.Notifications' requested by ':1.10' (uid=1000 pid=5024 comm="/usr/bin/notify-send -u critical -i dialog-warning")
00:06:40 stretch su[5022]: pam_unix(su:session): session closed for user lluis
00:06:40 stretch sudo[4987]: pam_unix(sudo:session): session closed for user root
00:06:50 stretch org.freedesktop.Notifications[3636]: org.kde.knotifications: WaitForName: Service was not registered within timeout
00:06:50 stretch dbus-daemon[3636]: [session uid=1000 pid=3634] Activated service 'org.freedesktop.Notifications' failed: Process org.freedesktop.Notifications exited with status 1

```
adding DBUS_SESSION_BUS_ADDRESS to /etc/needrestart/notify.d/400-notify-send solves it

**Comment by RolandRosenfeld** [comment]
On my system the above patch does not fully close the issue, since DBUS_SESSION_BUS_ADDRESS is set, but not exported, as suggested by @lluis.  So it's not available in the notify-send call, which results in a timeout instead of a notification on my system.
I just reported this as an issue to Debian: http://bugs.debian.org/1024426
