### ISSUE TITLE
SLES12: rpmquery --filesbypkg vs. rpm -q --filesbypkg

### ISSUE THREAD

**Issue by shartge** [liske/needrestart#81]
During testing of needrestart on SLES12(SP3) we found out that "`rpmquery --filesbypkg`" does not work but "`rpm -q --filesbypkg`" does and provides the necessary output for the rpm hook to work.

Suggestion: change every occurance of `rpmquery` to `rpm -q` which seems much more portable to me.

**Comment by liske** [comment]
Thanks!
