### ISSUE TITLE
how to test 600-mail?

### ISSUE THREAD

**Issue by mdik** [liske/needrestart#82]
Hi,

I would like to configure one email address that notifications are sent to, no matter in which circumstances needrestart is executed.

The following might work:
https://github.com/mdik/needrestart/commit/558f457359613686563c88b331164477e4c8d3ff

But how would I test it?

Sincerely,

Malte

**Comment by liske** [comment]
The README in [ex/notify.d/](https://github.com/liske/needrestart/blob/master/ex/notify.d/README.needrestart) describes how the scripts are run by needrestart (env variables & file descriptors). If you adopt the environment you can run the scripts manually.
