### ISSUE TITLE
needrestart (via nagios) and perl interpreter based services

### ISSUE THREAD

**Issue by thierrydevriendt** [liske/needrestart#83]
Hello,

We use needrestart with nagios to monitor our servers.

There is a nagios server that call needrestart script via NRPE on all servers. NRPE is running under the nagios account on the monitored servers. As needrestart needs to be run under the root account, we also use sudo.

Our setup is:

On monitored server:
Config of nrpe: command[check_needrestart]=sudo /usr/sbin/needrestart -p
Config of sudo: nagios ALL=(root) NOPASSWD: /usr/sbin/needrestart

On nagios server, the launched command is:

./check_nrpe -H monitored-server -c check_needrestart

The command returns "Unable to read output"
Inside the nrpe logs of the monitored server, I can see: Exit code 3, no returns.

This issue only happens when the monitored servers has specific services launched with the perl interpreter (i.e.:   usr/bin/perl /usr/share/backuppc/bin/BackupPC -d)

If I run needrestart directly on the console of the monitored server, it works (under the root and nagios account). It's only when the script is invoked via nrpe.
If I add this configuration into the blacklist binaries (needrestart.conf), then it works like a charm also with nrpe:
qr(^/usr/bin/perl),

Nagios server is running Debian 8.
Monitored server is running Debian 9 with nrpe 3.0.1.
needrestart version: 2.11

Could you help me?
Thanks.
T.

**Comment by liske** [comment]
There is no TTY if needrestart is run by nrpe - maybe this might trigger some bug. Could you try to run it via SSH so there is no TTY: `ssh -T nrpe-host needrestart` ?

**Comment by GMLudo** [comment]
Maybe because requiretty seems disabled by default now in sudo ?
https://serverfault.com/questions/111064/sudoers-how-to-disable-requiretty-per-user

**Comment by liske** [comment]
If `requiretty` is present in *sudoers* than the *check_needrestart* will fail to run since NRPE does not have a TTY. It was enabled by default before Debian 8 or 9 and might still be if the monitored server has been dist-upgraded.

**Comment by thierrrydevriendt** [comment]
Hello,
It's a new Debian 9 installation, so indeed, requiretty is disabled by default in sudo.

If I configure nagios user to /bin/false in /etc/passwd (monitored server):
via NRPE:
./check_nrpe -H xx.xx -c check_needrestart
NRPE: Unable to read output

via SSH:
ssh -T nagios@xx.xx sudo /usr/sbin/needrestart -p
returns nothing

If I configure nagios user to /bin/bash in /etc/passwd (monitored server):
via SSH:
ssh -T nagios@xx.xx sudo /usr/sbin/needrestart -p
OK - Kernel: 4.9.0-4-amd64, Services: none, Containers: none, Sessions: none|Kernel=0;0;;0;2 Services=0;;0;0 Containers=0;;0;0 Sessions=0;0;;0

It works. However:

via NRPE:
./check_nrpe -H xx.xx -c check_needrestart
NRPE: Unable to read output

**Comment by thierrrydevriendt** [comment]
Hello,
Could you help us for this?
Thanks.
T.

**Comment by andabata** [comment]
We had the same issue, it seems that nrpe-server is now started with PrivateTmp=true (with systemd)
and that breaks needrestart

We think it might be related to line 451,
                            unless($path =~ m@^/tmp/@ ||

**Comment by renini** [comment]
$ cat /etc/systemd/system/nagios-nrpe-server.service.d/override.conf
[Service]
PrivateTmp=false

thats the workaround for us for now...

**Comment by thierrrydevriendt** [comment]
Hello All,

Thank you a lot for this. This also fixed it for us...

Thank you @andabata @renini 

Regards,
Thierry

**Comment by GMLudo** [comment]
Hi,

It's maybe necessary to open an issue on https://github.com/NagiosEnterprises/nrpe ?
The default parameter for systemd service comes here:
https://github.com/NagiosEnterprises/nrpe/blob/master/startup/default-service.in#L23

It looks similar to this issue: https://github.com/NagiosEnterprises/nrpe/issues/149
Where @hardstar propose to change the shebang to remove -T option from the Perl command interpreter.

I don't know what is the best: Disable private tmp to be still compatible with the most Perl nagios-plugins, or request a change inside all Perl nagios-plugins ?

Regards.
