### ISSUE TITLE
 NeedRestart::UI assumes STDOUT is a terminal, fails to run when piped

### ISSUE THREAD

**Issue by guillaume-uH57J9** [liske/needrestart#86]
I encounter issues running needrestart in an unattended manner because NeedRestart::UI assumes STDOUT is a terminal. 

This bug was previously logged downstream as [Debian bug #859387](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=859387). I am logging this here as I believe the issue is upstream. 

The following command: 
`DEBIAN_FRONTEND=noninteractive needrestart -q -r l | logger -s`

Gives the following error: 
`Unable to get Terminal Size. The TIOCGWINSZ ioctl didn't work. The COLUMNS and LINES environment variables didn't work. The resize program didn't work. The stty program didn't work. at /usr/share/perl5/NeedRestart/UI.pm line 50.`

Explanation of the command: 
* Variable `DEBIAN_FRONTEND=noninteractive` tells debconf not to wait for user interaction regarding kernel updates. This is a workaround for #67
* Command `logger -s` sends the output to syslog and STDERR. The actual command is not important, the catch here is NeedRestart::UI doesn't expect the output to be piped to another process, it expect instead STDOUT to be a terminal.

**Comment by guillaume-uH57J9** [comment]
As an alternative I've tried using the batch mode as follows: 
`needrestart -q -b`

The batch mode seems to work fine without terminal, as its name suggest, but it seems to ignore the quiet option and always prints needrestart's version. So still no solution in sight.

**Comment by guillaume-uH57J9** [comment]
I submitted a pull request along with an example command to run needrestart in a unattended manner, and produce a human-readable output: 

`needrestart -u NeedRestart::UI::stdio -q -r l | logger -s`

**Comment by liske** [comment]
Hi,

the batch options does indeed ignore the quiet option intentional. The batch option prints all findings in a parsable format (used by DE-IBH/apt-dater) for further processing so the quiet option does not make any sense. I'm considering to add another option to needrestart to enforce a unattended/non-interactive mode.

HTH,
Thomas
