### ISSUE TITLE
user mode

### ISSUE THREAD

**Issue by glensc** [liske/needrestart#9]
seems needrestart can operate in "user mode", so it should be installed to `bin` not `sbin` if it's useful for non-root users.

aside: documentation about "user mode" is also lacking, only code says in few places "running in user mode"

```perl
    # user-mode: skip foreign processes 
    next if($uid && $ptable->{$pid}->{uid} != $uid); 
```

```perl
# running mode (user or root)
my $uid = $<;
if($uid) {
...
    print STDERR "$LOGPREF running in user-mode\n" if($nrconf{verbose});
}
else {
    print STDERR "$LOGPREF running in root-mode\n" if($nrconf{verbose});
}


```

**Comment by liske** [comment]
The user mode was added for https://github.com/liske/needrestart-session. IMHO needrestart should be kept in /usr/sbin since running needrestart by unprivileged users is not the expected use case.

**Comment by glensc** [comment]
ok. did not know about separate project.
