### ISSUE TITLE
needrestart wants to restart LXC containers again and again

### ISSUE THREAD

**Issue by larsen0815** [liske/needrestart#90]
Although needrestart has already restarted two LXC containers on the first run, they are shown again on the next run.

Details: https://pastebin.com/1KGUtkyk

Previously (must have been with Debian Jessie), I was able to prevent this by using "$nrconf{override_rc}->{q(^lxc)} = 0;", but this no longer applies, as containers are apparently handled differently.

Debian Stretch
needrestart 2.11-3

**Comment by larsen0815** [comment]
After I noticed the problem, I have stopped Puppet that is controlling the conf-file containing the override_rc setting. Now that I have posted this issued, I have started Puppet and needrestart no longer shows the containers as needing to be restarted.

**Comment by liske** [comment]
To override the restart behavior of containers there is the `override_cont` setting.
