### ISSUE TITLE
Difference between user and root output

### ISSUE THREAD

**Issue by stdedos** [liske/needrestart#96]
Is this discrepancy expected?

```
sntentos@optiplex-9010 [2017-12-19 12:18:58]:~/.installs/needrestart$ (master u=) needrestart 
Scanning processes...                                                                                                                                                                                       
Your outdated processes:
chrome[3154, 3624, 3136, 2917, 3397, 3297, 3514, 3169, 3734, 3457, 3483, 3354, 3332, 3120, 3314, 3531, 3177, 3010, 3695, 3570, 3373, 3718, 3064, 3551, 9611, 3639, 3425, 2913, 3255], compiz[1980],
 evolution[2629], nacl_helper[2914]
```
vs
```
sntentos@optiplex-9010 [2017-12-19 12:19:01]:~/.installs/needrestart$ (master u=) sudo needrestart 
Scanning processes...                                                                                                                                                                                       
Scanning candidates...                                                                                                                                                                                      
Scanning linux images...                                                                                                                                                                                    
Running kernel seems to be up-to-date.
No services need to be restarted.
No containers need to be restarted.
No user sessions are running outdated binaries.

```

**Comment by stdedos** [comment]
_note that restarting chrome does not change the output of user enough, i.e._
```
sntentos@optiplex-9010 [2017-12-19 12:21:08]:~/.installs/needrestart$ (master u=) needrestart 
Scanning processes...                                                                                                                                                                                       
Your outdated processes:
chrome[12875, 13121, 12708, 12832, 13062, 12986, 13043, 13200, 12725, 13027, 12962, 12876, 12624, 12862, 13154, 13010, 12699, 12785, 12628, 12849, 13169, 12821, 13090], compiz[1980], evolution[2629],
 nacl_helper[12625]
```

**Comment by liske** [comment]
Could you please provide the output of `needrestart -v` for both cases? Maybe needrestart in unable to relate chrome to any user session (or service or container) so it is ignored.

**Comment by stdedos** [comment]
There you go:

[needrestart_root.log](https://github.com/liske/needrestart/files/1575025/needrestart_root.log)
[needrestart_user.log](https://github.com/liske/needrestart/files/1575026/needrestart_user.log)

```
sntentos@optiplex-9010 [2017-12-20 11:49:12]:~$ needrestart -v &> needrestart_user.log
sntentos@optiplex-9010 [2017-12-20 11:49:14]:~$  sudo bash 
[sudo] password for sntentos: 
*** System restart required ***
linux-base
linux-base
linux-base
root@optiplex-9010 [2017-12-20 11:49:20]:~#  unset HISTFILE
root@optiplex-9010 [2017-12-20 11:49:23]:~# needrestart -v &> needrestart_root.log

```

However, if you will still need extra info, kindly ask them asap - since I won't have access to that computer until next year.


_On a sidenote, I noticed something about dependencies error. I was wondering, is there an "automated" way to install the needed dependencies? If yes, why `make install` didn't prompt anything? :confused:_

**Comment by liske** [comment]
How is chrome installed and run? It does not look like an ordinary distri package. I'm wondering why there are so many processes mapping executable temporary files.

Sitenote: Not while installing from source. Take a look at the [`INSTALL.md`](https://github.com/liske/needrestart/blob/master/INSTALL.md) for the required dependencies.

**Comment by stdedos** [comment]
I wouldn't say so ... 😕 
```
sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
sudo apt-get install google-chrome-stable
```

_PS: Yeah, I did. I just had to manually install/update cpan, cpanm, and then the listed dependencies one by one :( Maybe they can be given as a dependency if needed? 😕_

**Comment by stdedos** [comment]
@liske So, are there more info still needed, or it's simply on your backlog?

**Comment by liske** [comment]
Could you give the packages from [Debian experimental](https://packages.debian.org/experimental/needrestart) a try? Please ensure that you remove any manually installed parts (needrestart and CPAN stuff) before installing. If the problem still exists with this version another bundle of debugging logs (`needrestart -v`) are required.

**Comment by stdedos** [comment]
Well, I guess I can check on Tuesday. Don't hold your breath until that time 😉
